import { Check, Copy } from "lucide-react";
import { Button } from "@components/ui/Button";
import { Badge } from "@components/ui/Badge";
import { Input } from "@components/ui/Input";
import { Select } from "@components/ui/Select";
import { SuperAdminPlanPreviewCard } from "@pages/admin/components/SuperAdminPlanPreviewCard";
import { inr, toIst } from "./shared";

export function PriceSummary({ pricing }: { pricing: any }) {
  return <div className="rounded-[5px] border border-slate-200 bg-slate-50 p-3 text-xs"><div className="font-black text-slate-900 mb-2">Payment Summary</div><div className="grid grid-cols-2 gap-2"><span>Original Price</span><span className="text-right">{inr(pricing.original)}</span><span>Discount</span><span className="text-right">{inr(pricing.discountAmount)} ({pricing.discountPercent}%)</span><span>Discounted Price</span><span className="text-right">{inr(pricing.discounted)}</span><span>GST ({pricing.gstPercent}%)</span><span className="text-right">{inr(pricing.gstAmount)}</span><span className="font-black">Total Payable</span><span className="text-right font-black">{inr(pricing.payable)}</span></div></div>;
}

export function PlanModal(props: any) {
  return <div className="fixed inset-0 z-[999] bg-slate-900/45 backdrop-blur-sm p-4 flex items-center justify-center" onClick={props.onClose}><div className="w-full max-w-6xl max-h-[92vh] overflow-y-auto rounded-[5px] border border-slate-200 bg-white p-5 md:p-6" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between mb-4"><h3 className="text-lg font-black text-slate-900">{props.title}</h3><Button variant="ghost" onClick={props.onClose}>Close</Button></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><div className="space-y-3"><Select label="Plan" value={props.selectedPlanId} onChange={(e) => props.setSelectedPlanId(e.target.value)}><option value="">Select plan</option>{props.plans.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</Select><Input label="Duration Months" type="number" min={1} max={24} value={String(props.durationMonths)} onChange={(e) => props.setDurationMonths(Number(e.target.value || 1))} />{!props.hideReason ? <Input label="Reason" value={props.reason} onChange={(e) => props.setReason(e.target.value)} placeholder="Override reason" /> : null}<PriceSummary pricing={props.pricing} /><div className="flex items-center gap-2"><Button disabled={!props.selectedPlanId} onClick={props.onProceed}>{props.proceedLabel}</Button></div></div><div className="sticky top-3">{props.currentPlan ? <SuperAdminPlanPreviewCard name={props.currentPlan.name} description={props.currentPlan.description} discountedPriceRupees={String(Math.round(Number(props.currentPlan.pricing?.discountedPricePaise || 0) / 100))} badgeText={props.currentPlan.ui?.badgeText || props.currentPlan.badgeText} recommended={Boolean(props.currentPlan.ui?.recommended || props.currentPlan.recommended)} displayFeatures={props.currentPlan.displayFeatures || []} unavailableFeatures={props.currentPlan.unavailableFeatures || []} /> : <div className="rounded-[5px] border border-slate-200 p-4 text-sm text-slate-500">Select a plan to preview.</div>}</div></div></div></div>;
}

export function ConfirmModal({ title, text, onNo, onYes, loading, yesLabel }: any) {
  return <div className="fixed inset-0 z-[999] bg-slate-900/50 p-4 flex items-center justify-center" onClick={onNo}><div className="w-full max-w-md rounded-[5px] border border-slate-200 bg-white p-5" onClick={(e) => e.stopPropagation()}><div className="text-base font-black text-slate-900">{title}</div><div className="text-sm text-slate-600 mt-2">{text}</div><div className="mt-4 flex items-center justify-end gap-2"><Button variant="ghost" onClick={onNo}>No</Button><Button disabled={loading} onClick={onYes}>{loading ? "Please wait..." : yesLabel}</Button></div></div></div>;
}

export function PaymentLinkResultModal({ generatedLink, copied, onClose, onCopy }: any) {
  if (!generatedLink) return null;
  return <div className="fixed inset-0 z-[999] bg-slate-900/45 backdrop-blur-sm p-4 flex items-center justify-center"><div className="w-full max-w-2xl rounded-[5px] border border-slate-200 bg-white p-5 md:p-6"><div className="text-lg font-black text-slate-900">Payment Link Generated</div><div className="mt-3 rounded-[5px] border border-slate-200 bg-slate-50 p-3 text-xs break-all">{generatedLink.purchaseUrl}</div><div className="mt-4 flex items-center justify-end gap-2"><Button variant="ghost" onClick={onClose}>Close</Button><Button onClick={onCopy}>{copied ? <Check size={16} /> : <Copy size={16} />}<span className="ml-2">{copied ? "Copied" : "Copy Link"}</span></Button></div></div></div>;
}

export function PaymentLinkDetailModal({ row, onClose, onDisable }: any) {
  const amount = row.amountSummary || {};
  return <div className="fixed inset-0 z-[999] bg-slate-900/45 backdrop-blur-sm p-4 flex items-center justify-center" onClick={onClose}><div className="w-full max-w-5xl max-h-[90vh] overflow-y-auto rounded-[5px] border border-slate-200 bg-white p-5 md:p-6" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between mb-4"><h3 className="text-lg font-black text-slate-900">Payment Link Details</h3><Button variant="ghost" onClick={onClose}>Close</Button></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="rounded-[5px] border border-slate-200 p-4 space-y-2 text-sm"><div><span className="font-black">Status:</span> {row.status}</div><div><span className="font-black">Single Use:</span> {row.singleUse ? "Yes" : "No"}</div><div><span className="font-black">Plan:</span> {row.planName || row.planSlug || "-"}</div><div><span className="font-black">Duration:</span> {row.durationMonths} month(s)</div><div><span className="font-black">Link Valid Until:</span> {row.expiresAt ? new Date(row.expiresAt).toLocaleString() : "-"}</div><PriceSummary pricing={{ original: amount.originalPricePaise || 0, discountAmount: amount.discountAmountPaise || 0, discountPercent: amount.discountPercent || 0, discounted: amount.discountedPricePaise || 0, gstPercent: amount.gstPercent || 0, gstAmount: amount.gstAmountPaise || 0, payable: amount.payableAmountPaise || 0 }} /></div><div><SuperAdminPlanPreviewCard name={row.planName || "Plan"} description={`Payment link for ${row.durationMonths} month(s)`} discountedPriceRupees={String(Math.round(Number(amount.discountedPricePaise || 0) / 100))} badgeText={`Status: ${row.status}`} recommended={false} displayFeatures={[`Total payable ${inr(amount.payableAmountPaise)}`, `GST ${amount.gstPercent || 0}%`, `Single use link`]} unavailableFeatures={row.status === "active" ? ["Disable if payment is pending"] : []} /></div></div><div className="mt-4 flex items-center justify-end gap-2">{row.status === "active" ? <Button variant="danger" onClick={onDisable}>Disable Link</Button> : null}</div></div></div>;
}

export function HistoryDetailModal({ row, onClose }: any) {
  return <div className="fixed inset-0 z-[999] bg-slate-900/45 backdrop-blur-sm p-4 flex items-center justify-center" onClick={onClose}><div className="w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-[5px] border border-slate-200 bg-white p-5 md:p-6" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between mb-4"><h3 className="text-lg font-black text-slate-900">Subscription History Detail</h3><Button variant="ghost" onClick={onClose}>Close</Button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm"><div className="rounded-[5px] border border-slate-200 p-3"><div className="text-xs font-black uppercase text-slate-500 mb-2">Plan</div><div className="font-semibold text-slate-900">{row.planName || "-"}</div><div className="text-xs text-slate-600 mt-1">Slug: {row.planSlug || "-"}</div><div className="text-xs text-slate-600 mt-1">Status: {row.status || "-"}</div></div><div className="rounded-[5px] border border-slate-200 p-3"><div className="text-xs font-black uppercase text-slate-500 mb-2">Validity</div><div className="text-xs text-slate-700">From: {toIst(row.currentPeriodStart)}</div><div className="text-xs text-slate-700 mt-1">Until: {toIst(row.currentPeriodEnd)}</div><div className="text-xs text-slate-700 mt-1">Duration: {row.durationMonths || "-"} month(s)</div></div><div className="rounded-[5px] border border-slate-200 p-3"><div className="text-xs font-black uppercase text-slate-500 mb-2">Payment</div><div className="text-xs text-slate-700">Type: {row.paymentType || "-"}</div><div className="text-xs text-slate-700 mt-1">Transaction ID: {row.transactionId || "-"}</div><div className="text-xs text-slate-700 mt-1">Amount: {inr(row.amountPaidPaise)}</div><div className="text-xs text-slate-700 mt-1">GST: {inr(row.gstAmountPaise)}</div><div className="text-xs font-bold text-slate-900 mt-1">Payable: {inr(row.payableAmountPaise)}</div></div><div className="rounded-[5px] border border-slate-200 p-3"><div className="text-xs font-black uppercase text-slate-500 mb-2">Audit</div><div className="text-xs text-slate-700">Created (IST): {toIst(row.createdAt)}</div><div className="text-xs text-slate-700 mt-1">Auto Renew: {row.autoRenewEnabled ? "Enabled" : "Disabled"}</div></div></div></div></div>;
}

export function UsageCard({ title, data }: { title: string; data?: any }) {
  const used = Number(data?.used || 0); const limit = data?.limit; const remaining = data?.remaining; const percent = Number(data?.percent || 0);
  return <div className="rounded-[5px] border border-slate-200 p-3"><div className="text-xs font-black uppercase tracking-wider text-slate-500">{title}</div><div className="mt-2 text-lg font-black text-slate-900">{used}{limit == null ? " / Infinity" : ` / ${limit}`}</div><div className="text-xs text-slate-600 mt-1">Remaining: {remaining == null ? "Infinity" : remaining}</div><div className="mt-2 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-brand-600" style={{ width: `${Math.max(4, Math.min(100, percent))}%` }} /></div></div>;
}

export function JsonCard({ title, data }: { title: string; data: any }) {
  return <div className="rounded-[5px] border border-slate-200 p-3"><div className="text-xs font-black uppercase text-slate-500 mb-2">{title}</div><pre className="text-xs text-slate-700 whitespace-pre-wrap break-all">{JSON.stringify(data, null, 2)}</pre></div>;
}

export function ListCard({ row, onClick }: any) {
  return <div className="rounded-[5px] border border-slate-200 p-3 cursor-pointer hover:bg-slate-50" onClick={onClick}><div className="flex items-center justify-between"><div className="text-sm font-bold text-slate-900">{row.planName || row.planSlug || row.id || "-"}</div><Badge className="text-[10px]">{row.status || "-"}</Badge></div></div>;
}
