import { Alert } from "@components/ui/Alert";
import { Button } from "@components/ui/Button";
import { Input } from "@components/ui/Input";
import { Textarea } from "@components/ui/Textarea";
import { SuperAdminPlanPreviewCard } from "@pages/admin/components/SuperAdminPlanPreviewCard";
import { createRow, inr, statusColor } from "./shared";
import { FeatureRowsBuilder } from "./FeatureRowsBuilder";

export function EditorView(props: any) {
  const { isCreate, isEdit, isReview, navigate, editor, setEditor, isFreePlan, uniqueFeatureRows, preview, saving, saveEditor, setConfirmAction, error, availableFunctionalityKeys, availableLimitKeys } = props;
  const readOnly = false;
  const title = isCreate ? "Create Plan" : isEdit ? "Edit Plan" : isReview ? "Review Plan" : "View Plan";
  const status = String(editor.status || "in_review");
  const displayFeatures = Array.isArray(editor.displayFeatures) && editor.displayFeatures.length ? editor.displayFeatures : uniqueFeatureRows.filter((r: any) => r.included && String(r.label || "").trim()).map((r: any) => r.label);
  const unavailableFeatures = Array.isArray(editor.unavailableFeatures) && editor.unavailableFeatures.length ? editor.unavailableFeatures : uniqueFeatureRows.filter((r: any) => !r.included && String(r.label || "").trim()).map((r: any) => r.label);
  return (
    <div className="flex flex-col gap-6 p-4 md:p-8 pb-20">
      <div className="flex items-center justify-between"><div><h1 className="text-3xl font-black tracking-tight text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500 font-medium">Status: <span className={statusColor(status)}>{status}</span></p></div><div className="flex gap-2 flex-wrap"><Button variant="ghost" onClick={() => navigate("/super-admin/subscription-plans")}>Back to Plans</Button>{editor.id && !isFreePlan ? <Button onClick={() => setConfirmAction({ id: editor.id, action: "publish", name: editor.name || "this plan" })}>Publish</Button> : null}{editor.id && !isFreePlan ? <Button variant="ghost" onClick={() => setConfirmAction({ id: editor.id, action: "disable", name: editor.name || "this plan" })}>Disable</Button> : null}</div></div>
      {error ? <Alert variant="danger">{error}</Alert> : null}
      <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_420px] gap-6 items-start">
        <div className="lg:sticky lg:top-24 lg:max-h-[calc(100vh-7rem)] lg:overflow-y-auto"><div className="w-full rounded-[5px] border border-slate-200 bg-white p-5 md:p-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Input label="Plan Name" value={editor.name} onChange={(e) => setEditor((s: any) => ({ ...s, name: e.target.value }))} disabled={readOnly} />
          <Input label="Slug (optional)" value={editor.slug} onChange={(e) => setEditor((s: any) => ({ ...s, slug: e.target.value }))} disabled={readOnly} />
          <div className="md:col-span-2"><Textarea label="Description" value={editor.description} onChange={(e) => setEditor((s: any) => ({ ...s, description: e.target.value }))} disabled={readOnly} /></div>
          <Input label="Original Price (Rupees)" value={editor.originalPriceRupees} onChange={(e) => setEditor((s: any) => ({ ...s, originalPriceRupees: e.target.value.replace(/[^\d.]/g, "") }))} disabled={readOnly || isFreePlan} />
          <Input label="Discounted Price (Rupees)" value={editor.discountedPriceRupees} onChange={(e) => setEditor((s: any) => ({ ...s, discountedPriceRupees: e.target.value.replace(/[^\d.]/g, "") }))} disabled={readOnly || isFreePlan} />
          <Input label="GST Percent" value={editor.gstPercent} onChange={(e) => setEditor((s: any) => ({ ...s, gstPercent: e.target.value.replace(/[^\d.]/g, "") }))} disabled={readOnly || isFreePlan} />
          <Input label="Tax Mode" value={isFreePlan ? "N/A (free)" : "exclusive"} disabled />
          <Input label="Button Text" value={editor.buttonText} onChange={(e) => setEditor((s: any) => ({ ...s, buttonText: e.target.value }))} disabled={readOnly} />
          <div><div className="mb-1 text-xs font-semibold text-slate-500 uppercase">Sort Order</div><select className="w-full rounded-[5px] border border-slate-200 px-3 py-2.5 text-sm" value={String(editor.sortOrder || 1)} onChange={(e) => setEditor((s: any) => ({ ...s, sortOrder: Number(e.target.value || 1) }))} disabled={readOnly}><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></div>
          <div className="md:col-span-2 grid grid-cols-1 md:grid-cols-1 gap-3 text-xs font-semibold text-slate-700"><label><input type="checkbox" checked={editor.recommended} onChange={(e) => setEditor((s: any) => ({ ...s, recommended: e.target.checked }))} disabled={readOnly} /> recommended (only one)</label></div>
          <div className="md:col-span-2 border border-slate-200 rounded-[5px] p-3"><div className="flex justify-between items-center mb-2"><div className="text-sm font-black text-slate-900">Feature Builder</div>{!readOnly && !isFreePlan ? <Button variant="outline" onClick={() => setEditor((s: any) => ({ ...s, featureRows: [...s.featureRows, createRow()] }))}>Add Row</Button> : null}</div>
            {isFreePlan ? <div className="space-y-3"><div className="text-xs font-semibold text-slate-500">Free plan include/exclude is fixed. You can update only limits below.</div></div> : <FeatureRowsBuilder editor={editor} setEditor={setEditor} readOnly={readOnly} isFreePlan={isFreePlan} availableFunctionalityKeys={availableFunctionalityKeys} availableLimitKeys={availableLimitKeys} />}
          </div>
          {isFreePlan ? <div className="md:col-span-2 border border-slate-200 rounded-[5px] p-3"><div className="text-sm font-black text-slate-900 mb-2">Free Plan Limits</div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Input label="Max Contacts / Month" value={editor?.freeLimits?.maxContacts || ""} onChange={(e) => setEditor((s: any) => ({ ...s, freeLimits: { ...(s.freeLimits || {}), maxContacts: e.target.value.replace(/[^\d]/g, "") } }))} /><Input label="Max Templates / Month" value={editor?.freeLimits?.maxTemplates || ""} onChange={(e) => setEditor((s: any) => ({ ...s, freeLimits: { ...(s.freeLimits || {}), maxTemplates: e.target.value.replace(/[^\d]/g, "") } }))} /><Input label="Max Campaigns / Month" value={editor?.freeLimits?.maxCampaignsPerMonth || ""} onChange={(e) => setEditor((s: any) => ({ ...s, freeLimits: { ...(s.freeLimits || {}), maxCampaignsPerMonth: e.target.value.replace(/[^\d]/g, "") } }))} /><Input label="Max Contact Exports / Month" value={editor?.freeLimits?.maxContactsExport || ""} onChange={(e) => setEditor((s: any) => ({ ...s, freeLimits: { ...(s.freeLimits || {}), maxContactsExport: e.target.value.replace(/[^\d]/g, "") } }))} /></div></div> : null}
          <div className="md:col-span-2"><Textarea label="Review Note" value={editor.reviewNote} onChange={(e) => setEditor((s: any) => ({ ...s, reviewNote: e.target.value }))} disabled={readOnly} /></div>
          {preview && !isFreePlan ? <div className="col-span-2 rounded-[5px] border border-slate-200 bg-slate-50 p-4"><div className="text-sm font-black text-slate-900">Price Preview</div><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-3"><div className="rounded-[5px] border border-slate-200 bg-white px-3 py-2"><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Original</div><div className="mt-1 text-sm font-black text-slate-900">{inr(preview.originalPricePaise)}</div></div><div className="rounded-[5px] border border-slate-200 bg-white px-3 py-2"><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Discounted</div><div className="mt-1 text-sm font-black text-slate-900">{inr(preview.discountedPricePaise)}</div></div><div className="rounded-[5px] border border-emerald-200 bg-emerald-50 px-3 py-2"><div className="text-[10px] font-semibold uppercase tracking-wide text-emerald-700">Save</div><div className="mt-1 text-sm font-black text-emerald-800">{inr(preview.discountAmountPaise)}</div></div><div className="rounded-[5px] border border-slate-200 bg-white px-3 py-2"><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Discount</div><div className="mt-1 text-sm font-black text-slate-900">{preview.discountPercent}%</div></div><div className="rounded-[5px] border border-slate-200 bg-white px-3 py-2"><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">GST</div><div className="mt-1 text-sm font-black text-slate-900">{inr(preview.gstAmountPaise)}</div></div><div className="rounded-[5px] border border-brand-200 bg-brand-50 px-3 py-2"><div className="text-[10px] font-semibold uppercase tracking-wide text-brand-700">Payable</div><div className="mt-1 text-sm font-black text-brand-800">{inr(preview.payableAmountPaise)}</div></div></div></div> : null}
        </div>{!readOnly ? <div className="sticky bottom-0 bg-white pt-4 flex justify-end gap-2"><Button variant="ghost" onClick={() => navigate("/super-admin/subscription-plans")}>Cancel</Button><Button onClick={() => void saveEditor()} disabled={saving || !editor.name}>{saving ? "Saving..." : (isFreePlan ? "Save Free Plan" : "Save (In Review)")}</Button></div> : null}</div></div>
        <div className="lg:sticky lg:top-24 lg:max-h-[calc(100vh-7rem)] lg:overflow-y-auto"><SuperAdminPlanPreviewCard name={editor.name} description={editor.description} discountedPriceRupees={editor.discountedPriceRupees} recommended={editor.recommended} badgeText={editor.badgeText} discountAmountPaise={Number(preview?.discountAmountPaise || 0)} displayFeatures={displayFeatures} unavailableFeatures={unavailableFeatures} /></div>
      </div>
    </div>
  );
}
