import { Button } from "@components/ui/Button";
import { Input } from "@components/ui/Input";
import { PAGE_ACCESS_OPTIONS } from "./shared";

export function FeatureRowsBuilder({ editor, setEditor, readOnly, isFreePlan, availableFunctionalityKeys, availableLimitKeys }: any) {
  return (
    <div className="space-y-3">
      {editor.featureRows.map((row: any, idx: number) => (
        <div key={idx} className="border border-slate-100 rounded-[5px] p-3 space-y-3">
          <Input label="Label" value={row.label} onChange={(e) => setEditor((s: any) => { const next = [...s.featureRows]; next[idx] = { ...next[idx], label: e.target.value }; return { ...s, featureRows: next }; })} disabled={readOnly || isFreePlan} />
          <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
            <div><div className="mb-1 text-xs font-semibold text-slate-500 uppercase">Type</div><select className="w-full rounded-[5px] border border-slate-200 px-2 py-2" value={row.type} onChange={(e) => setEditor((s: any) => { const nextType = e.target.value as "text" | "page"; const next = [...s.featureRows]; next[idx] = { ...next[idx], type: nextType, pageAccessKey: nextType === "page" ? next[idx].pageAccessKey : "", targetType: nextType === "page" ? next[idx].targetType : "", functionalityKey: nextType === "page" ? next[idx].functionalityKey : "", limitKey: nextType === "page" ? next[idx].limitKey : "", value: nextType === "page" ? next[idx].value : "", unlimited: nextType === "page" ? next[idx].unlimited : false }; return { ...s, featureRows: next }; })} disabled={readOnly || isFreePlan}><option value="text">text</option><option value="page">page</option></select></div>
            <div>{row.type === "page" ? <><div className="mb-1 text-xs font-semibold text-slate-500 uppercase">Page Access</div><select className="w-full rounded-[5px] border border-slate-200 px-2 py-2" value={row.pageAccessKey} onChange={(e) => setEditor((s: any) => { const pageAccessKey = e.target.value; const autoFunctionality = pageAccessKey === "campaignsPageAccess" ? "campaignApiAccess" : ""; const next = [...s.featureRows]; next[idx] = { ...next[idx], pageAccessKey, targetType: "", functionalityKey: autoFunctionality, limitKey: "", value: "", unlimited: false }; return { ...s, featureRows: next }; })} disabled={readOnly || isFreePlan}><option value="">Select page access</option>{PAGE_ACCESS_OPTIONS.map((k) => <option key={k} value={k}>{k}</option>)}</select></> : <div className="h-full flex items-end"><div className="text-xs font-semibold text-slate-400">Text row: no mapping required</div></div>}</div>
            <div>{row.type === "page" ? <div className="h-full flex items-end"><div className="w-full"><div className="mb-1 text-xs font-semibold text-slate-500 uppercase">Map To</div><select className="w-full rounded-[5px] border border-slate-200 px-2 py-2" value={row.targetType} onChange={(e) => setEditor((s: any) => { const targetType = e.target.value as "functionality" | "limit" | ""; const next = [...s.featureRows]; next[idx] = { ...next[idx], targetType, functionalityKey: targetType === "functionality" ? next[idx].functionalityKey : "", limitKey: targetType === "limit" ? next[idx].limitKey : "", value: "", unlimited: false }; return { ...s, featureRows: next }; })} disabled={readOnly || isFreePlan || !row.pageAccessKey}><option value="">None</option><option value="functionality">functionality</option><option value="limit">limit</option></select></div></div> : null}</div>
          </div>
          {row.type === "page" && row.targetType ? <div className="grid grid-cols-1 md:grid-cols-2 gap-2">{row.targetType === "functionality" ? <div><div className="mb-1 text-xs font-semibold text-slate-500 uppercase">Functionality</div><select className="w-full rounded-[5px] border border-slate-200 px-2 py-2" value={row.functionalityKey} onChange={(e) => setEditor((s: any) => { const next = [...s.featureRows]; next[idx] = { ...next[idx], functionalityKey: e.target.value }; return { ...s, featureRows: next }; })} disabled={readOnly || isFreePlan || !row.pageAccessKey}><option value="">Select functionality</option>{availableFunctionalityKeys(idx, row.pageAccessKey).map((k: string) => <option key={k} value={k}>{k}</option>)}</select></div> : null}{row.targetType === "limit" ? <><div><div className="mb-1 text-xs font-semibold text-slate-500 uppercase">Limit Key</div><select className="w-full rounded-[5px] border border-slate-200 px-2 py-2" value={row.limitKey} onChange={(e) => setEditor((s: any) => { const next = [...s.featureRows]; next[idx] = { ...next[idx], limitKey: e.target.value }; return { ...s, featureRows: next }; })} disabled={readOnly || isFreePlan || !row.pageAccessKey}><option value="">Select limit</option>{availableLimitKeys(idx, row.pageAccessKey).map((k: string) => <option key={k} value={k}>{k}</option>)}</select></div><Input label="Value" value={row.value} onChange={(e) => setEditor((s: any) => { const next = [...s.featureRows]; next[idx] = { ...next[idx], value: e.target.value.replace(/[^\d]/g, "") }; return { ...s, featureRows: next }; })} disabled={readOnly || isFreePlan || row.unlimited} /></> : null}</div> : null}
          <div className="grid grid-cols-1 md:grid-cols-[minmax(0,1fr)_auto_auto_auto] gap-2 items-end"><div />
            <div className="inline-flex items-center gap-4 pb-2 text-xs font-semibold text-slate-700"><label className="inline-flex items-center gap-2"><input type="radio" name={`feature-row-included-${idx}`} checked={row.included === true} onChange={() => setEditor((s: any) => { const next = [...s.featureRows]; next[idx] = { ...next[idx], included: true }; return { ...s, featureRows: next }; })} disabled={readOnly || isFreePlan} />included</label><label className="inline-flex items-center gap-2"><input type="radio" name={`feature-row-included-${idx}`} checked={row.included === false} onChange={() => setEditor((s: any) => { const next = [...s.featureRows]; next[idx] = { ...next[idx], included: false }; return { ...s, featureRows: next }; })} disabled={readOnly || isFreePlan} />excluded</label></div>
            <label className={`text-xs font-semibold inline-flex items-center gap-2 pb-2 ${row.type === "page" && row.targetType === "limit" ? "text-slate-700" : "text-slate-400"}`}><input type="checkbox" checked={row.unlimited} onChange={(e) => setEditor((s: any) => { const next = [...s.featureRows]; next[idx] = { ...next[idx], unlimited: e.target.checked }; return { ...s, featureRows: next }; })} disabled={readOnly || isFreePlan || row.type !== "page" || row.targetType !== "limit"} />unlimited</label>
            <div className="pb-1">{!readOnly && !isFreePlan ? <Button variant="outline" onClick={() => setEditor((s: any) => ({ ...s, featureRows: s.featureRows.filter((_: any, i: number) => i !== idx) }))}>Remove</Button> : null}</div>
          </div>
        </div>
      ))}
    </div>
  );
}
