export const FUNCTIONALITY_KEYS = [
  "dashboardPageAccess", "templatesPageAccess", "campaignsPageAccess", "contactsPageAccess", "inboxPageAccess", "crmPageAccess", "flowsPageAccess", "walletPageAccess", "linksPageAccess", "automationPageAccess", "activityPageAccess", "apiKeysPageAccess", "apiReportsPageAccess", "campaignApiAccess", "externalChatApiAccess", "crmAccess", "employeeAccess", "leadDistributionAccess", "analyticsAccess", "exportAccess", "automationAccess", "apiKeyAccess",
];
export const LIMIT_KEYS = ["maxContacts", "maxTemplates", "maxEmployees", "maxApiKeys", "maxCampaignsPerMonth", "maxContactsExport", "maxStorageMb"];
export const PAGE_ACCESS_OPTIONS = ["dashboardPageAccess", "templatesPageAccess", "campaignsPageAccess", "contactsPageAccess", "inboxPageAccess", "crmPageAccess", "flowsPageAccess", "walletPageAccess", "linksPageAccess", "automationPageAccess", "activityPageAccess", "apiKeysPageAccess", "apiReportsPageAccess"];
export const PAGE_BINDING: Record<string, { functionality: string[]; limits: string[] }> = {
  dashboardPageAccess: { functionality: [], limits: [] }, templatesPageAccess: { functionality: [], limits: ["maxTemplates"] }, campaignsPageAccess: { functionality: ["campaignApiAccess"], limits: ["maxCampaignsPerMonth"] }, contactsPageAccess: { functionality: [], limits: ["maxContacts", "maxContactsExport"] }, inboxPageAccess: { functionality: ["apiKeyAccess"], limits: [] }, crmPageAccess: { functionality: ["crmAccess", "employeeAccess", "leadDistributionAccess"], limits: ["maxEmployees"] }, flowsPageAccess: { functionality: ["automationAccess"], limits: [] }, walletPageAccess: { functionality: [], limits: [] }, linksPageAccess: { functionality: ["analyticsAccess"], limits: [] }, automationPageAccess: { functionality: ["automationAccess"], limits: [] }, activityPageAccess: { functionality: ["analyticsAccess"], limits: [] }, apiKeysPageAccess: { functionality: ["apiKeyAccess"], limits: ["maxApiKeys"] }, apiReportsPageAccess: { functionality: ["analyticsAccess"], limits: [] },
};
export type FeatureRow = { label: string; type: "page" | "text"; pageAccessKey: string; targetType: "functionality" | "limit" | ""; functionalityKey: string; limitKey: string; value: string; included: boolean; sortOrder: number; unlimited: boolean };
export const createRow = (): FeatureRow => ({ label: "", type: "text", pageAccessKey: "", targetType: "", functionalityKey: "", limitKey: "", value: "", included: true, sortOrder: 0, unlimited: false });
export const inr = (paise?: number | null) => (paise == null ? "-" : `Rs ${Math.round(Number(paise) / 100).toLocaleString("en-IN")}`);
export const statusColor = (status: string) => status === "published" ? "text-emerald-700" : status === "in_review" ? "text-amber-700" : status === "disabled" ? "text-rose-700" : "text-slate-700";
export function dedupeBy<T>(items: T[], keyGetter: (item: T) => string) { const seen = new Set<string>(); const out: T[] = []; for (const item of items) { const key = keyGetter(item); if (!key || seen.has(key)) continue; seen.add(key); out.push(item); } return out; }
