import { useState } from "react";
import { Button } from "@components/ui/Button";
import { Input } from "@components/ui/Input";
import { useCommerce, useCommerceAction, useCommerceQuery } from "./commerceContext";
import { Check, ErrorNotice, fieldClass, label, Pager, Panel, QueryState } from "./ui";
import { DeliveryDetails, useDeliveryRefresh } from "./DeliveryManagement";
import type { Courier, Delivery, Outlet } from "./DeliveryManagement";
import type { Page } from "./types";
import ZoneMap from "./ZoneMap";
type Zone = { id: string; revision: number; name: string; outletId: string; latitude: number; longitude: number; radiusMetres: number; active: boolean; autoAssign: boolean; priority: number; prepToleranceSeconds: number; maxWaitSeconds: number; maxTripSeconds: number; maxDetourSeconds: number; stopSeconds: number };
function useRows<T>(path: string) {
  const { environment } = useCommerce(), [cursors, setCursors] = useState<string[]>([]);
  const q = useCommerceQuery<Page<T> & { enabled?: boolean }>(path, { environment, limit: 25, cursor: cursors.at(-1) }, true);
  return { ...q, pager: <Pager next={q.data?.nextCursor} back={cursors.length ? () => setCursors((v) => v.slice(0, -1)) : undefined} onNext={() => setCursors((v) => [...v, q.data!.nextCursor!])} /> };
}
const numeric = [["radiusMetres", "Customer radius (metres)", 100, 50000], ["priority", "Zone priority (lowest first)", 0, 100], ["prepToleranceSeconds", "Ready-time difference (seconds)", 0, 1800], ["maxWaitSeconds", "Maximum pickup wait (seconds)", 0, 1800], ["maxTripSeconds", "Maximum trip travel (seconds)", 300, 7200], ["maxDetourSeconds", "Maximum extra travel per customer (seconds)", 0, 3600], ["stopSeconds", "Allowance per customer stop (seconds)", 0, 600]] as const;
function ZoneForm({ zone, saved, close }: { zone?: Zone; saved(): void; close(): void }) {
  const outlets = useRows<Outlet>("/outlets"), action = useCommerceAction();
  const [form, setForm] = useState(() => ({ name: zone?.name || "", outletId: zone?.outletId || "", latitude: zone?.latitude ?? 22.5, longitude: zone?.longitude ?? 79, radiusMetres: zone?.radiusMetres || 4000, active: zone?.active ?? true, autoAssign: zone?.autoAssign ?? false, priority: zone?.priority ?? 10, prepToleranceSeconds: zone?.prepToleranceSeconds ?? 300, maxWaitSeconds: zone?.maxWaitSeconds ?? 300, maxTripSeconds: zone?.maxTripSeconds ?? 3600, maxDetourSeconds: zone?.maxDetourSeconds ?? 600, stopSeconds: zone?.stopSeconds ?? 120 }));
  return <Panel title={zone ? "Edit delivery zone" : "Create delivery zone"}><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); void action.run(zone ? `/delivery-zones/${zone.id}` : "/delivery-zones", { ...form, ...(zone ? { revision: zone.revision } : {}) }, saved, zone ? "PATCH" : "POST"); }}><fieldset disabled={action.busy} className="space-y-4">
    <Input label="Zone name" required maxLength={150} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><label>Pickup outlet<select required disabled={!!zone} className={fieldClass} value={form.outletId} onChange={(e) => { const outlet = outlets.data?.items.find((o) => o.id === e.target.value); setForm({ ...form, outletId: e.target.value, ...(outlet ? { latitude: outlet.latitude, longitude: outlet.longitude } : {}) }); }}><option value="">Select outlet</option>{zone && !outlets.data?.items.some((o) => o.id === zone.outletId) && <option value={zone.outletId}>Current outlet</option>}{outlets.data?.items.map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><QueryState {...outlets} />{!zone && outlets.pager}
    <ZoneMap value={form} onChange={(p) => setForm((old) => ({ ...old, ...p }))} /><div className="grid gap-3 sm:grid-cols-2"><Input label="Centre latitude" type="number" step="any" min={-90} max={90} required value={form.latitude} onChange={(e) => setForm({ ...form, latitude: Number(e.target.value) })} /><Input label="Centre longitude" type="number" step="any" min={-180} max={180} required value={form.longitude} onChange={(e) => setForm({ ...form, longitude: Number(e.target.value) })} />{numeric.map(([key, title, min, max]) => <Input key={key} label={title} type="number" step={1} min={min} max={max} required value={form[key]} onChange={(e) => setForm({ ...form, [key]: Number(e.target.value) })} />)}</div>
    <Check label="Zone active" checked={form.active} onChange={(active) => setForm({ ...form, active })} /><Check label="Zone auto assignment ON" checked={form.autoAssign} onChange={(autoAssign) => setForm({ ...form, autoAssign })} /><p className="text-sm">Global Auto Dispatch and courier auto assignment must also be ON. Changes apply to new additions; existing orders are not removed.</p>
    </fieldset><ErrorNotice message={action.error} /><div className="flex gap-2"><Button type="submit" disabled={action.busy}>Save zone</Button><Button type="button" variant="outline" onClick={close}>Close</Button></div></form></Panel>;
}
function CapacityForm({ courier, saved }: { courier: Courier; saved(): void }) {
  const zones = useRows<Zone>("/delivery-zones"), action = useCommerceAction();
  const [capacity, setCapacity] = useState(courier.batchCapacity || 1), [auto, setAuto] = useState(courier.batchAutoAssign || false), [allowed, setAllowed] = useState(courier.allowedZoneIds || []);
  const [mode, setMode] = useState(courier.batchMode || "fixed_zone"), [radius, setRadius] = useState(courier.batchRadiusMetres || 4000), [pickup, setPickup] = useState(courier.pickupRadiusMetres || 8000);
  return <div className="space-y-3 rounded border p-3"><p>{courier.name}: {courier.batchLoad || 0}/{courier.batchCapacity || 1} slots occupied. Pending offers count toward capacity.</p><Input label="Maximum simultaneous orders" type="number" min={1} max={30} step={1} value={capacity} onChange={(e) => setCapacity(Number(e.target.value))} /><label>Batch area<select className={fieldClass} value={mode} onChange={(e) => setMode(e.target.value)} disabled={!!courier.currentTripId}><option value="fixed_zone">Fixed delivery zones</option><option value="first_customer">First customer radius</option></select></label><Input label="First customer radius (metres)" type="number" min={100} max={50000} value={radius} onChange={(e) => setRadius(Number(e.target.value))} /><Input label="Pickup radius (metres)" type="number" min={100} max={50000} value={pickup} onChange={(e) => setPickup(Number(e.target.value))} /><Check label="Courier auto assignment ON" checked={auto} onChange={setAuto} /><QueryState {...zones} />{zones.data?.items.filter((z) => courier.allowedOutletIds.includes(z.outletId)).map((z) => <Check key={z.id} label={`${z.name} (${z.radiusMetres / 1000} km)`} checked={allowed.includes(z.id)} onChange={(yes) => setAllowed(yes ? [...allowed, z.id] : allowed.filter((id) => id !== z.id))} />)}{zones.pager}<ErrorNotice message={action.error} /><Button disabled={action.busy || capacity < 1 || capacity > 30} onClick={() => action.run(`/couriers/${courier.id}/batching`, { revision: courier.revision, batchCapacity: capacity, batchMode: mode, batchRadiusMetres: radius, pickupRadiusMetres: pickup, batchAutoAssign: auto, allowedZoneIds: allowed }, saved, "PATCH")}>Save courier capacity</Button></div>;
}
function BatchDispatch() {
  const deliveries = useRows<Delivery>("/deliveries"), couriers = useRows<Courier>("/couriers"), zones = useRows<Zone>("/delivery-zones"), { can } = useCommerce(), action = useCommerceAction();
  const [selected, setSelected] = useState<Delivery[]>([]), [courierId, setCourier] = useState(""), [zoneId, setZone] = useState(""), [edit, setEdit] = useState<Courier | null>(null), [detail, setDetail] = useState("");
  const [preview, setPreview] = useState<{ routeSeconds: number; totalOrders: number; capacity: number } | null>(null), [intent, setIntent] = useState("");
  const reset = () => { setPreview(null); setIntent(""); };
  useDeliveryRefresh(deliveries.reload, 5000, deliveries.loading);
  if (zones.data?.enabled === false) return <Panel title="Batch dispatch"><p>Batch dispatch is not enabled. Existing single-order dispatch remains available.</p></Panel>;
  const payload = (key: string) => ({ ...(zoneId ? { zoneId } : {}), courierId, idempotencyKey: key, deliveries: selected.map((r) => ({ id: r.id, revision: r.revision })) });
  return <><Panel title="Courier capacity"><QueryState {...couriers} />{couriers.data?.items.map((c) => <div key={c.id} className="flex items-center justify-between border-b py-2"><span>{c.name} · {c.batchLoad || 0}/{c.batchCapacity || 1} slots · Auto {c.batchAutoAssign ? "ON" : "OFF"}</span>{can("commerce.delivery.manage") && <Button variant="outline" onClick={() => setEdit(c)}>Configure</Button>}</div>)}{couriers.pager}{edit && <CapacityForm key={`${edit.id}:${edit.revision}`} courier={edit} saved={() => { setEdit(null); couriers.reload(); }} />}</Panel>
    <Panel title="Assign orders together"><p>Same merchant, outlet and environment only. Maximum 30 orders; ready times, zone radius, road travel and capacity are checked by the server. Rider acceptance is required for each new order.</p><QueryState {...deliveries} /><QueryState {...zones} />
      <fieldset disabled={!can("commerce.delivery.manage") || action.busy} className="space-y-3"><label>Delivery zone<select className={fieldClass} value={zoneId} onChange={(e) => { setZone(e.target.value); reset(); }}><option value="">First customer radius (courier setting)</option>{zoneId && !zones.data?.items.some((z) => z.id === zoneId) && <option value={zoneId}>Selected zone</option>}{zones.data?.items.map((z) => <option key={z.id} value={z.id}>{z.name}</option>)}</select></label>{zones.pager}<label>Courier<select className={fieldClass} value={courierId} onChange={(e) => { setCourier(e.target.value); reset(); }}><option value="">Select courier</option>{courierId && !couriers.data?.items.some((c) => c.id === courierId) && <option value={courierId}>Selected courier</option>}{couriers.data?.items.map((c) => <option key={c.id} value={c.id}>{c.name} ({c.batchLoad || 0}/{c.batchCapacity || 1})</option>)}</select></label>
      <p>{selected.length} orders selected. Capacity is a maximum; orders do not wait for the trip to fill.</p>{selected.length > 0 && <Button variant="outline" onClick={() => { setSelected([]); reset(); }}>Clear selection</Button>}
      {deliveries.data?.items.filter((r) => ["awaiting_rider", "awaiting_manual_assignment"].includes(r.status)).map((r) => <Check key={r.id} label={`${r.orderNumber || r.id} · ${r.pickup?.name || "Outlet"} · ${r.destination?.city || "Destination"} · ${label(r.preparationStatus)}`} checked={selected.some((s) => s.id === r.id)} disabled={selected.length >= 30 && !selected.some((s) => s.id === r.id)} onChange={(yes) => { setSelected(yes ? [...selected, r] : selected.filter((s) => s.id !== r.id)); reset(); }} />)}{deliveries.pager}
      <Button disabled={!selected.length || !courierId || action.busy} onClick={() => { const key = crypto.randomUUID(); setIntent(key); setPreview(null); void action.run("/delivery-trips/preview", payload(key), (data) => setPreview(data as typeof preview)); }}>Review assignment</Button>
      {preview && <div className="rounded border p-3"><p>Google Maps road estimate: {Math.ceil(preview.routeSeconds / 60)} minutes including customer stops. {preview.totalOrders}/{preview.capacity} slots after assignment. Estimates may change.</p><Button disabled={action.busy} onClick={() => action.run("/delivery-trips/assign", payload(intent), () => { setSelected([]); reset(); deliveries.reload(); couriers.reload(); })}>Confirm offers to courier</Button></div>}</fieldset><ErrorNotice message={action.error} retry={() => { reset(); setSelected([]); deliveries.reload(); couriers.reload(); }} /></Panel>
    <Panel title="Manage assigned deliveries"><p>Open a delivery to withdraw an offer or reassign before pickup. Then select it above for the next courier.</p>{deliveries.data?.items.filter((r) => !["pending_dispatch", "cancelled", "delivered"].includes(r.status)).map((r) => <Button key={r.id} variant="outline" onClick={() => setDetail(r.id)}>{r.orderNumber || r.id} · {label(r.status)}</Button>)}</Panel>{detail && <DeliveryDetails key={detail} id={detail} />}</>;
}
function Zones() {
  const zones = useRows<Zone>("/delivery-zones"), { can } = useCommerce(), [edit, setEdit] = useState<Zone | "new" | null>(null);
  return <><Panel title="Delivery Zones" action={zones.data?.enabled && can("commerce.delivery.manage") && <Button onClick={() => setEdit("new")}>Add zone</Button>}><QueryState {...zones} />{zones.data?.enabled === false && <p>Batching requires administrator setup before zones can be configured.</p>}{zones.data?.items.map((z) => <div key={z.id} className="flex justify-between border-b py-3"><div><p className="font-semibold">{z.name}</p><p>{z.radiusMetres / 1000} km radius · Priority {z.priority} · {z.active ? "Active" : "Inactive"} · Auto {z.autoAssign ? "ON" : "OFF"}</p></div>{can("commerce.delivery.manage") && <Button variant="outline" onClick={() => setEdit(z)}>Edit zone</Button>}</div>)}{zones.pager}</Panel>{edit && <ZoneForm key={edit === "new" ? "new" : edit.id} zone={edit === "new" ? undefined : edit} close={() => setEdit(null)} saved={() => { setEdit(null); zones.reload(); }} />}</>;
}
export default function BatchingManagement({ section }: { section: string }) {
  return section === "batch-dispatch" ? <BatchDispatch /> : <Zones />;
}
