import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "@components/ui/Button";
import { Input } from "@components/ui/Input";
import { Modal } from "@components/ui/Modal";
import { useCommerce, useCommerceAction, useCommerceQuery } from "./commerceContext";
import { Check, date, ErrorNotice, fieldClass, label, Pager, Panel, QueryState, Status } from "./ui";
import type { Page, Product } from "./types";
import { useDeliverySocket } from "./deliverySocket";
import BranchDispatch from "./BranchDispatch";
import BatchingManagement from "./BatchingManagement";
import { DispatchSettings, RoutingAssistance } from "./RoutingAssistance";
type Hours = { day: number; open: string; close: string };
export type Outlet = { id: string; name: string; address: string; latitude: number; longitude: number; active: boolean; prepMinutes: number; radiusMetres: number; openingHours: Hours[]; revision: number };
export type Courier = { id: string; name: string; phone: string; active: boolean; online: boolean; vehicle: string; currentDeliveryId: string | null; currentTripId?: string | null; address?: string; batchMode?: string; batchRadiusMetres?: number; pickupRadiusMetres?: number; batchLoad?: number; batchCapacity?: number; batchAutoAssign?: boolean; allowedZoneIds?: string[]; allowedOutletIds: string[]; revision: number; location?: { latitude: number; longitude: number; accuracy: number; receivedAt: string } };
export type Delivery = { id: string; orderId: string; orderNumber?: string; paymentStatus?: string; outletId: string; status: string; autoDispatchPaused?: boolean; autoAttempts?: number; pickedUpAt?: string | null; preparationStatus: string; prepMinutes: number; readyAt: string; courierId: string | null; offerExpiresAt: string; revision: number; lastReason: string; pickup?: { name: string; address: string; latitude: number; longitude: number }; destination?: { name: string; phone: string; line1: string; line2: string; city: string; location: { latitude: number; longitude: number } } };
export function useDeliveryRefresh(reload: () => void, interval = 5000, loading = false) {
  const current = useRef(reload); current.current = () => { if (!loading) reload(); };
  useEffect(() => { const refresh = () => { if (!document.hidden) current.current(); }; const timer = window.setInterval(refresh, interval); window.addEventListener("online", refresh); document.addEventListener("visibilitychange", refresh);
    return () => { clearInterval(timer); window.removeEventListener("online", refresh); document.removeEventListener("visibilitychange", refresh); }; }, [interval]);
}
function usePage<T>(path: string) {
  const [cursors, setCursors] = useState<string[]>([]), { environment } = useCommerce();
  const query = useCommerceQuery<Page<T>>(path, { limit: 25, cursor: cursors.at(-1), environment }, true);
  return { ...query, pager: <Pager next={query.data?.nextCursor} back={cursors.length ? () => setCursors((v) => v.slice(0, -1)) : undefined} onNext={() => setCursors((v) => [...v, query.data!.nextCursor!])} /> };
}
function OutletForm({ outlet, close, saved }: { outlet?: Outlet; close: () => void; saved: () => void }) {
  const [form, setForm] = useState({ name: outlet?.name || "", address: outlet?.address || "", latitude: outlet?.latitude ?? "", longitude: outlet?.longitude ?? "", active: outlet?.active ?? true,
    prepMinutes: outlet?.prepMinutes || 15, radiusMetres: outlet?.radiusMetres || 8000, openingHours: outlet?.openingHours || [] as Hours[] });
  const action = useCommerceAction();
  return <Modal open title={outlet ? "Edit branch" : "Create branch"} onClose={close}><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); void action.run(outlet ? `/outlets/${outlet.id}` : "/outlets", { ...form, latitude: Number(form.latitude), longitude: Number(form.longitude), ...(outlet ? { revision: outlet.revision } : {}) }, saved, outlet ? "PATCH" : "POST"); }}>
    <fieldset disabled={action.busy} className="space-y-3"><Input label="Branch name" required maxLength={150} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input label="Pickup address" required maxLength={1000} value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} />
      <div className="grid grid-cols-2 gap-3"><Input label="Latitude" type="number" step="any" min={-90} max={90} required value={form.latitude} onChange={(e) => setForm({ ...form, latitude: e.target.value })} /><Input label="Longitude" type="number" step="any" min={-180} max={180} required value={form.longitude} onChange={(e) => setForm({ ...form, longitude: e.target.value })} />
      <Input label="Preparation minutes" type="number" min={1} max={240} value={form.prepMinutes} onChange={(e) => setForm({ ...form, prepMinutes: Number(e.target.value) })} /><Input label="Service radius (metres)" type="number" min={100} max={50000} value={form.radiusMetres} onChange={(e) => setForm({ ...form, radiusMetres: Number(e.target.value) })} /></div>
      <Check label="Active branch" checked={form.active} onChange={(active) => setForm({ ...form, active })} /><p className="text-sm">Opening hours · Asia/Kolkata. Unselected days are closed.</p>
      {["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].map((day, i) => { const hours = form.openingHours.find((h) => h.day === i); return <div key={day} className="flex items-center gap-2"><Check label={day} checked={!!hours} onChange={(v) => setForm({ ...form, openingHours: v ? [...form.openingHours, { day: i, open: "09:00", close: "22:00" }] : form.openingHours.filter((h) => h.day !== i) })} />{hours && ["open", "close"].map((key) => <input aria-label={`${day} ${key}`} key={key} type="time" required value={hours[key as "open" | "close"]} onChange={(e) => setForm({ ...form, openingHours: form.openingHours.map((h) => h.day === i ? { ...h, [key]: e.target.value } : h) })} />)}</div>; })}
    </fieldset><ErrorNotice message={action.error} /><Button type="submit" disabled={action.busy}>Save branch</Button></form></Modal>;
}
function BranchStock({ outlet }: { outlet: Outlet }) {
  const query = usePage<{ id: string; productId: string; revision: number; stockOnHand: number; stockReserved: number; available: boolean }>(`/outlets/${outlet.id}/stock`);
  const [productCursors, setProductCursors] = useState<string[]>([]), products = useCommerceQuery<{ products: Product[]; nextCursor: string }>("/products", { limit: 25, cursor: productCursors.at(-1) }), action = useCommerceAction();
  const [selected, setSelected] = useState(""), [count, setCount] = useState(0), [available, setAvailable] = useState(true), [confirm, setConfirm] = useState(false);
  const row = query.data?.items.find((r) => r.productId === selected), product = products.data?.products.find((p) => p.id === selected);
  return <Panel title={`Branch stock · ${outlet.name}`}><QueryState {...query} /><QueryState {...products} /><ErrorNotice message={action.error} />
    {query.data?.items.map((r) => <div key={r.id} className="flex justify-between text-sm"><span>{products.data?.products.find((p) => p.id === r.productId)?.name || r.productId} · {r.stockOnHand} on hand / {r.stockReserved} reserved</span><Button size="sm" variant="outline" onClick={() => { setSelected(r.productId); setCount(r.stockOnHand); setAvailable(r.available); }}>Edit</Button></div>)}{query.pager}
    <label className="block text-sm">Product<select className={fieldClass} value={selected} onChange={(e) => { setSelected(e.target.value); setConfirm(false); setCount(0); }}><option value="">Select product</option>{selected && !product && <option value={selected}>Selected branch product</option>}{products.data?.products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <Pager next={products.data?.nextCursor} back={productCursors.length ? () => { setProductCursors((v) => v.slice(0, -1)); setSelected(""); } : undefined} onNext={() => { setProductCursors((v) => [...v, products.data!.nextCursor]); setSelected(""); }} />
    <Input label="Stock on hand" type="number" min={row?.stockReserved || 0} max={100000000} value={count} onChange={(e) => setCount(Number(e.target.value))} /><Check label="Available at this branch" checked={available} onChange={setAvailable} />
    <Button disabled={!selected || action.busy || query.loading} onClick={() => action.run(`/outlets/${outlet.id}/stock/${selected}`, { revision: row?.revision || 0, stockOnHand: count, available }, query.reload, "PUT")}>Save branch stock</Button>
    <p className="text-sm">For an unmigrated product, move its existing inventory to this initial branch first. Other branches receive no automatic stock. Existing reservations remain with their original branch.</p>
    <Check label="Move this product's existing stock and reservations to this branch." checked={confirm} onChange={setConfirm} />
    <Button variant="outline" disabled={!product || !confirm || action.busy} onClick={() => action.run(`/outlets/${outlet.id}/stock/${selected}/migrate`, { revision: product!.revision, confirm: true }, () => { query.reload(); products.reload(); setConfirm(false); })}>Initialize branch inventory</Button>
  </Panel>;
}
function Outlets() {
  const [dispatch, setDispatch] = useState("");
  const query = usePage<Outlet>("/outlets"), { can } = useCommerce(), [edit, setEdit] = useState<Outlet | "new" | null>(null), [stock, setStock] = useState<Outlet | null>(null);
  return <><Panel title="Restaurants & Branches" action={can("commerce.delivery.manage") && <Button onClick={() => setEdit("new")}>Add branch</Button>}><QueryState {...query} empty={!query.data?.items.length} />
    {query.data?.items.map((o) => <div key={o.id} className="border-b py-3"><p className="font-semibold">{o.name} · {o.active ? "Active" : "Inactive"}</p><p className="text-sm">{o.address} · Preparation {o.prepMinutes} min · Radius {o.radiusMetres / 1000} km</p>{can("commerce.delivery.manage") && <div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setEdit(o)}>Edit branch</Button><Button variant="outline" size="sm" onClick={() => setDispatch(o.id)}>Orders and couriers</Button>{can("commerce.products.manage") && <Button variant="outline" size="sm" onClick={() => setStock(o)}>Manage stock</Button>}</div>}</div>)}{query.pager}</Panel>
    {edit && <OutletForm outlet={edit === "new" ? undefined : edit} close={() => setEdit(null)} saved={() => { setEdit(null); query.reload(); }} />}{stock && <BranchStock key={stock.id} outlet={stock} />}{dispatch && <BranchDispatch key={dispatch} outletId={dispatch} />}</>;
}
function Couriers() {
  const query = usePage<Courier>("/couriers"), outlets = usePage<Outlet>("/outlets"), action = useCommerceAction(), { can } = useCommerce();
  const [show, setShow] = useState(false), [editing, setEditing] = useState<Courier | null>(null), [form, setForm] = useState({ email: "", name: "", phone: "", address: "", batchCapacity: 1, batchMode: "first_customer", batchRadiusMetres: 4000, pickupRadiusMetres: 8000, batchAutoAssign: false, vehicle: "motorcycle", active: true, allowedOutletIds: [] as string[] });
  useDeliveryRefresh(query.reload, 5000, query.loading);
  return <Panel title="Courier Partners" action={can("commerce.delivery.manage") && <Button onClick={() => { setEditing(null); setForm({ email: "", name: "", phone: "", address: "", batchCapacity: 1, batchMode: "first_customer", batchRadiusMetres: 4000, pickupRadiusMetres: 8000, batchAutoAssign: false, vehicle: "motorcycle", active: true, allowedOutletIds: [] }); setShow(true); }}>Add rider</Button>}><QueryState {...query} empty={!query.data?.items.length} /><ErrorNotice message={action.error} /><Link to="/rider" className="underline">Open Rider app</Link>
    {query.data?.items.map((c) => <div key={c.id} className="border-b py-3"><p className="font-semibold">{c.name} · {c.phone}</p><p className="text-sm">{c.active ? c.online ? "Online" : "Offline" : "Suspended"} · {(c.currentDeliveryId || c.currentTripId) ? "Busy" : "Available"} · {c.vehicle} · GPS {date(c.location?.receivedAt)}</p>{can("commerce.delivery.manage") && <><Button size="sm" variant="outline" disabled={!!c.currentDeliveryId || !!c.currentTripId || action.busy} onClick={() => { setEditing(c); setForm({ email: "", name: c.name, phone: c.phone, address: c.address || "", batchCapacity: c.batchCapacity || 1, batchMode: c.batchMode || "fixed_zone", batchRadiusMetres: c.batchRadiusMetres || 4000, pickupRadiusMetres: c.pickupRadiusMetres || 8000, batchAutoAssign: c.batchAutoAssign || false, vehicle: c.vehicle, active: c.active, allowedOutletIds: c.allowedOutletIds }); setShow(true); }}>Edit rider</Button><Button size="sm" variant="outline" disabled={!!c.currentDeliveryId || !!c.currentTripId || action.busy} onClick={() => action.run(`/couriers/${c.id}`, { revision: c.revision, active: !c.active, allowedOutletIds: c.allowedOutletIds }, query.reload, "PATCH")}>{c.active ? "Suspend" : "Activate"}</Button></>}</div>)}{query.pager}
    {show && <Modal open title={editing ? "Edit courier partner" : "Add courier partner"} onClose={() => setShow(false)}><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); const { email, ...profile } = form; void action.run(editing ? `/couriers/${editing.id}` : "/couriers", editing ? { ...profile, revision: editing.revision } : { ...profile, email }, () => { setShow(false); query.reload(); }, editing ? "PATCH" : "POST"); }}><p className="text-sm">Rider must register a separate AIWizChat login first. This grants rider access only, without merchant workspace membership.</p>
      <fieldset disabled={action.busy} className="space-y-3">{(["name", "email", "phone"] as const).filter((key) => !editing || key !== "email").map((key) => <Input key={key} label={key} type={key === "email" ? "email" : "text"} required value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />)}<label>Vehicle<select className={fieldClass} value={form.vehicle} onChange={(e) => setForm({ ...form, vehicle: e.target.value })}>{["motorcycle", "bicycle", "car"].map((v) => <option key={v}>{v}</option>)}</select></label>
      <Input label="Courier address" maxLength={1000} value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} />
      <Input label="Maximum simultaneous orders" type="number" min={1} max={30} required value={form.batchCapacity} onChange={(e) => setForm({ ...form, batchCapacity: Number(e.target.value) })} />
      <label>Batch area<select className={fieldClass} value={form.batchMode} onChange={(e) => setForm({ ...form, batchMode: e.target.value })}><option value="first_customer">First customer radius</option><option value="fixed_zone">Fixed delivery zones</option></select></label>
      <Input label="First customer radius (metres)" type="number" min={100} max={50000} required value={form.batchRadiusMetres} onChange={(e) => setForm({ ...form, batchRadiusMetres: Number(e.target.value) })} />
      <Input label="Restaurant pickup radius (metres)" type="number" min={100} max={50000} required value={form.pickupRadiusMetres} onChange={(e) => setForm({ ...form, pickupRadiusMetres: Number(e.target.value) })} />
      <Check label="Courier auto assignment ON" checked={form.batchAutoAssign} onChange={(batchAutoAssign) => setForm({ ...form, batchAutoAssign })} /><p>Pending offers consume capacity. First customer fixes the batch centre; departure does not wait for capacity to fill. Fixed-zone couriers need allowed zones configured in Batch Dispatch.</p>
      <QueryState {...outlets} />{outlets.data?.items.map((o) => <Check key={o.id} label={o.name} checked={form.allowedOutletIds.includes(o.id)} onChange={(v) => setForm({ ...form, allowedOutletIds: v ? [...form.allowedOutletIds, o.id] : form.allowedOutletIds.filter((id) => id !== o.id) })} />)}{outlets.pager}</fieldset><ErrorNotice message={action.error} /><Button type="submit" disabled={action.busy || !form.allowedOutletIds.length}>{editing ? "Save rider profile" : "Create rider access"}</Button></form></Modal>}
  </Panel>;
}
function pickupDistance(a: Courier["location"], b: Delivery["pickup"]): string {
  if (!a || !b) return "distance unavailable";
  const rad = (v: number) => v * Math.PI / 180;
  const h = Math.sin(rad(b.latitude - a.latitude) / 2) ** 2 + Math.cos(rad(a.latitude)) * Math.cos(rad(b.latitude)) * Math.sin(rad(b.longitude - a.longitude) / 2) ** 2;
  return `${(6371 * 2 * Math.asin(Math.sqrt(Math.min(1, h)))).toFixed(1)} km to pickup`;
}
export function DeliveryDetails({ id }: { id: string }) {
  const query = useCommerceQuery<{ delivery: Delivery }>(`/deliveries/${id}`, undefined, true), couriers = usePage<Courier>("/couriers"), action = useCommerceAction(), { can } = useCommerce();
  const [reason, setReason] = useState(""), [courierId, setCourierId] = useState(""), [recommended, setRecommended] = useState<{ courierId: string; name: string } | null>(null), [link, setLink] = useState(""), intent = useRef<string | undefined>(undefined);
  const r = query.data?.delivery; useDeliveryRefresh(query.reload, 5000, query.loading); useDeliveryRefresh(couriers.reload, 5000, couriers.loading);
  useEffect(() => { if (["awaiting_rider", "awaiting_manual_assignment"].includes(r?.status || "")) intent.current = undefined; }, [r?.status]);
  const perform = (command: string) => { if (r) void action.run(`/deliveries/${id}/action`, { revision: r.revision, action: command, ...(reason ? { reason } : {}) }, query.reload); };
  return <Panel title="Delivery details"><QueryState {...query} /><ErrorNotice message={action.error} />{r && <><Status value={r.status} /><p>Preparation: {label(r.preparationStatus)} · Ready {date(r.readyAt)}</p><p>{r.pickup?.name} · {r.pickup?.address}</p><p>{r.destination?.name} · {r.destination?.line1}, {r.destination?.city}</p><Link className="underline" to={`/app/commerce/orders/${r.orderId}`}>Open order and payment</Link>
    {r.status === "awaiting_manual_assignment" && <p role="alert" className="rounded border border-amber-300 bg-amber-50 p-3">Manual assignment required. The order has not been automatically cancelled. Select an eligible rider below or resume automatic dispatch.</p>}
    {r.lastReason && <p className="text-sm">Last update: {r.lastReason}</p>}{can("commerce.delivery.manage") && <div className="space-y-3">
      {["awaiting_rider", "awaiting_manual_assignment", "offer_sent"].includes(r.status) && <div className="space-y-2"><p>{r.autoDispatchPaused ? "Automatic dispatch paused for this delivery." : "Automatic dispatch follows merchant settings."} Attempts: {r.autoAttempts || 0}.</p><Button variant="outline" disabled={action.busy} onClick={() => perform("pause_auto")}>Take manual control / withdraw offer</Button>{r.autoDispatchPaused && <Button variant="outline" disabled={action.busy} onClick={() => perform("resume_auto")}>Resume automatic dispatch</Button>}</div>}
      {r.status === "pending_dispatch" && <Button disabled={action.busy} onClick={() => perform("prepare")}>Start preparation after verified payment</Button>}
      {r.preparationStatus === "preparing" && <Button disabled={action.busy} onClick={() => perform("ready")}>Food ready for pickup</Button>}
      {["awaiting_rider", "awaiting_manual_assignment"].includes(r.status) && <><RoutingAssistance deliveryId={id} revision={r.revision} onSelect={(c) => { setCourierId(c.courierId); setRecommended(c); intent.current = undefined; }} /><QueryState {...couriers} /><label>Available rider<select className={fieldClass} value={courierId} onChange={(e) => { setCourierId(e.target.value); intent.current = undefined; }}><option value="">Select rider</option>{recommended && !couriers.data?.items.some((c) => c.id === recommended.courierId) && <option value={recommended.courierId}>{recommended.name} (recommended)</option>}{couriers.data?.items.filter((c) => c.active && c.online && !c.currentDeliveryId && c.allowedOutletIds.includes(r.outletId)).map((c) => <option key={c.id} value={c.id}>{c.name} · GPS {date(c.location?.receivedAt)}</option>)}</select></label>{couriers.pager}<p className="text-sm">Distances below are straight-line estimates to pickup, not travel times. Offer eligibility is checked by the server.</p><ul className="space-y-1 text-sm">{couriers.data?.items.filter((c) => c.allowedOutletIds.includes(r.outletId)).map((c) => <li key={c.id}>{c.name}: {c.active ? c.online ? "Online" : "Offline" : "Suspended"}, {c.currentDeliveryId ? "1 active delivery" : "0 active deliveries"}, {pickupDistance(c.location, r.pickup)}; GPS {date(c.location?.receivedAt)}{c.location ? `, accuracy ${Math.round(c.location.accuracy)} m` : ""}</li>)}</ul><Button disabled={!courierId || action.busy} onClick={() => { intent.current ||= crypto.randomUUID(); void action.run(`/deliveries/${id}/offers`, { revision: r.revision, courierId, idempotencyKey: intent.current }, query.reload); }}>Offer delivery to rider</Button></>}
      {r.status === "offer_sent" && <p>Offer expires {date(r.offerExpiresAt)}. The rider must accept.</p>}
      <Input label="Reason for reassignment or exception" maxLength={500} value={reason} onChange={(e) => setReason(e.target.value)} />
      <div className="flex flex-wrap gap-2">{(["assigned", "arrived_at_pickup", "offer_sent"].includes(r.status) || r.status === "exception" && !r.pickedUpAt) && <Button variant="outline" disabled={reason.length < 5 || action.busy} onClick={() => perform("reassign")}>Reassign</Button>}
      {["pending_dispatch", "awaiting_rider", "awaiting_manual_assignment", "offer_sent", "assigned", "arrived_at_pickup"].includes(r.status) && <Button variant="danger" disabled={reason.length < 5 || action.busy} onClick={() => perform("cancel")}>Cancel delivery</Button>}
      {can("commerce.delivery.override") && r.status === "exception" && <Button variant="danger" disabled={reason.length < 5 || action.busy} onClick={() => perform("cancel")}>Resolve failed / returned delivery</Button>}
      {can("commerce.delivery.override") && ["exception", "out_for_delivery"].includes(r.status) && <Button variant="danger" disabled={reason.length < 5 || action.busy} onClick={() => perform("override")}>Override delivery completion</Button>}</div>
      {!["delivered", "cancelled"].includes(r.status) && <Button variant="outline" disabled={action.busy} onClick={() => action.run<{ token: string }>(`/deliveries/${id}/tracking`, { revision: r.revision }, ({ token }) => { setLink(`${location.origin}/delivery-tracking#${token}`); query.reload(); })}>Create customer PIN / tracking link</Button>}
      {link && <div><p className="text-sm">Share privately with the customer. Creating another link replaces the previous link and PIN.</p><input aria-label="Customer tracking link" className={fieldClass} readOnly value={link} onFocus={(e) => e.target.select()} /></div>}
    </div>}</>}</Panel>;
}
export function DispatchAlerts() {
  const { environment, workspaceId } = useCommerce();
  const query = useCommerceQuery<Page<{ id: string; kind: string; reason: string; orderId: string }>>("/delivery-notifications", { environment, limit: 10 }, true);
  useDeliveryRefresh(query.reload, 5000, query.loading); useDeliverySocket(workspaceId, query.reload);
  const alerts = query.data?.items.filter((n) => ["awaiting_manual_assignment", "auto_dispatch_retry"].includes(n.kind)) || [];
  return <section aria-label="Recent operational alerts"><QueryState {...query} />{alerts.map((n) => <div role="alert" key={n.id} className="my-2 rounded border border-amber-300 bg-amber-50 p-3"><p>{label(n.kind)}: {n.reason}</p><Link className="underline" to={`/app/commerce/orders/${n.orderId}`}>Open order</Link></div>)}</section>;
}
function Dispatch() {
  const query = usePage<Delivery>("/deliveries"), [selected, setSelected] = useState(""); useDeliveryRefresh(query.reload, 5000, query.loading);
  return <><DispatchAlerts /><Panel title="Live Dispatch"><p className="text-sm">Dispatch follows your merchant settings. Orders enter this list after restaurant acceptance; assignment requires verified payment and preparation.</p><QueryState {...query} empty={!query.data?.items.length} />{query.data?.items.map((r) => <div key={r.id} className="flex items-center justify-between border-b py-3"><div><p className="font-semibold">{r.orderNumber || "Customer order"} - {r.pickup?.name}</p><Status value={r.status} /><p className="text-sm">Payment: {r.paymentStatus} - {r.destination?.city}</p><p className="text-sm">Preparation: {label(r.preparationStatus)}</p></div><Button variant="outline" size="sm" onClick={() => setSelected(r.id)}>Open delivery</Button></div>)}{query.pager}</Panel>{selected && <DeliveryDetails key={selected} id={selected} />}</>;
}
export function OrderDelivery({ orderId, revision, refreshed }: { orderId: string; revision: number; refreshed: () => void }) {
  const outlets = usePage<Outlet>("/outlets"), query = useCommerceQuery<{ delivery: Delivery | null; recommendation?: { outletId: string | null; name?: string; prepMinutes?: number; status: string } }>(`/orders/${orderId}/delivery`), action = useCommerceAction();
  const [branches, setBranches] = useState<{ candidates: { outletId: string; name: string; prepMinutes: number; roadMetres: number; etaSeconds: number }[]; suggestedOutletId: string | null; orderRevision: number } | null>(null);
  const [selection, setSelection] = useState("manual");
  const [outletId, setOutletId] = useState(""), [prepMinutes, setPrep] = useState(15);
  useEffect(() => { const r = query.data?.recommendation; if (!outletId && r?.outletId) { setOutletId(r.outletId); setPrep(r.prepMinutes || 15); setSelection("nearest"); } }, [query.data, outletId]);
  return <Panel title="Restaurant acceptance"><QueryState {...query} /><ErrorNotice message={action.error} />{query.data?.recommendation?.outletId && <p>Selected branch: {query.data.recommendation.name}. Restaurant acceptance pending until confirmed below.</p>}{query.data?.delivery && <p>Delivery: {label(query.data.delivery.status)} · <Link className="underline" to="/app/commerce/dispatch">Open Live Dispatch</Link></p>}
    {(!query.data?.delivery || query.data.delivery.status === "pending_dispatch") && <><Button variant="outline" disabled={action.busy} onClick={() => { setBranches(null); void action.run(`/orders/${orderId}/delivery/branches`, { revision }, (data) => { const result = data as NonNullable<typeof branches>; setBranches(result); if (result.suggestedOutletId) { setOutletId(result.suggestedOutletId); setSelection("nearest"); setPrep(result.candidates[0].prepMinutes); } }); }}>Find nearest eligible branch</Button>
    {branches && <div><p>Google Maps road distances; open branches with stock. Restaurant acceptance is still required.</p>{branches.orderRevision !== revision && <p>Order changed. Refresh branch recommendations.</p>}{!branches.candidates.length && <p>No eligible branch found. Review stock, opening hours and service radius.</p>}{branches.candidates.map((b) => <p key={b.outletId}>{b.name}: {(b.roadMetres / 1000).toFixed(1)} km, {Math.ceil(b.etaSeconds / 60)} min {b.outletId === branches.suggestedOutletId ? "(nearest)" : ""}</p>)}</div>}
    <QueryState {...outlets} /><label>Branch<select className={fieldClass} value={outletId} onChange={(e) => { setOutletId(e.target.value); setSelection("manual"); setPrep(outlets.data?.items.find((o) => o.id === e.target.value)?.prepMinutes || 15); }}><option value="">Select branch</option>{outletId && !outlets.data?.items.some((o) => o.id === outletId) && <option value={outletId}>{branches?.candidates.find((b) => b.outletId === outletId)?.name || query.data?.recommendation?.name || "Selected branch"}</option>}{outlets.data?.items.filter((o) => o.active).map((o) => <option value={o.id} key={o.id}>{o.name}</option>)}</select></label>{outlets.pager}
    <Input label="Estimated preparation minutes" type="number" min={1} max={240} value={prepMinutes} onChange={(e) => setPrep(Number(e.target.value))} /><Button disabled={!outletId || action.busy} onClick={() => action.run(`/orders/${orderId}/delivery`, { revision, outletId, prepMinutes, selection }, () => { query.reload(); refreshed(); })}>Accept at branch / change branch</Button><p className="text-sm">Then approve the order quote and create payment. Changes are locked once checkout starts. Use the order cancellation action to reject an unpaid order.</p></>}
  </Panel>;
}
function Notices({ overview }: { overview: boolean }) {
  const query = usePage<{ id: string; kind: string; orderId: string; createdAt: string; reason?: string }>("/delivery-notifications"); useDeliveryRefresh(query.reload, 5000, query.loading);
  const { workspaceId } = useCommerce(); useDeliverySocket(workspaceId, query.reload);
  return <Panel title={overview ? "Ecommerce overview" : "Reports & Activity"}><p className="text-sm">Persistent delivery activity, newest first. Open Live Dispatch for current delivery state.</p><QueryState {...query} empty={!query.data?.items.length} />{query.data?.items.map((n) => <div key={n.id} className="border-b py-3"><p>{label(n.kind)} · {date(n.createdAt)}</p>{n.reason && <p className="text-sm">{n.reason}</p>}<Link className="underline" to={`/app/commerce/orders/${n.orderId}`}>Open order</Link></div>)}{query.pager}</Panel>;
}
export default function DeliveryManagement({ section }: { section: string }) {
  return ["delivery-zones", "batch-dispatch"].includes(section) ? <BatchingManagement section={section} /> : section === "outlets" ? <Outlets /> : section === "couriers" ? <Couriers /> : section === "dispatch" ? <Dispatch /> : section === "dispatch-settings" ? <DispatchSettings /> : <Notices overview={section === "overview"} />;
}
