import { useEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "@components/ui/Button";
import { CommerceProvider, useCommerce, useCommerceAction, useCommerceQuery, useWorkspaceId } from "./commerceContext";
import type { Attempt, Collection, Order, Page, Product } from "./types";
import { Check, EnvironmentPicker, ErrorNotice, label, money, Pager, QueryState, Status } from "./ui";

type Props = { to: string; disabled?: boolean; onSent: () => void; preselectedCollectionIds?: string[] };
function PaymentAction({ order, send, busy }: { order: Order; send: (input: Record<string, unknown>) => void; busy: boolean }) {
  const { can } = useCommerce(), [inspect, setInspect] = useState(false);
  const query = useCommerceQuery<{ attempt: Attempt }>(inspect && can("commerce.payments.view") && order.activeAttemptId ? `/payments/attempts/${order.activeAttemptId}` : null);
  return <div className="space-y-2 border-b py-3"><div className="flex flex-wrap justify-between gap-2"><Link to={`/app/commerce/orders/${order.id}`} className="font-semibold text-brand-700 underline">{order.orderNumber} · {money(order.totalPaise)}</Link><Status value={order.status} /></div>{!inspect && can("commerce.payments.view") && order.activeAttemptId && <Button size="sm" variant="outline" onClick={() => setInspect(true)}>View payment request</Button>}<QueryState {...query} />
    {!order.activeAttemptId && order.paymentStatus !== "captured" && <p className="text-sm">Open this order to review details and create its payment request.</p>}{query.data?.attempt && <p className="text-sm">Payment request: {label(query.data.attempt.status)}{query.data.attempt.mode === "whatsapp_native" ? ". Native checkout includes a Review and Pay send attempt. Inspect its delivery in this chat." : ""}</p>}{query.data?.attempt.lastError && <ErrorNotice message={label(query.data.attempt.lastError)} />}{query.data?.attempt.paymentUrl && <Button size="sm" variant="outline" disabled={busy} onClick={() => send({ kind: "payment_request", attemptId: query.data!.attempt.id })}>Send payment request</Button>}</div>;
}
const eligible = (p: Product) => !p.archivedAt && p.available && p.syncStatus === "synced" && p.syncedRevision === p.revision && p.metaReviewStatus === "approved" && (!p.trackInventory || p.stockOnHand > p.stockReserved);

function InboxActions({ to, onSent, disabled, preselectedCollectionIds = [] }: Props) {
  const { can, access, environment, request } = useCommerce(), action = useCommerceAction();
  const [tab, setTab] = useState("products"), [mode, setMode] = useState<"custom" | "collections">(preselectedCollectionIds.length ? "collections" : "custom"), [selected, setSelected] = useState<string[]>([]), [cursors, setCursors] = useState<string[]>([]), [notice, setNotice] = useState("");
  const products = useCommerceQuery<{ products: Product[]; nextCursor: string | null }>(tab === "products" && mode === "custom" && can("commerce.products.view") && access.capabilities.catalog ? "/products" : null, { limit: 25, cursor: cursors.at(-1) });
  const orders = useCommerceQuery<Page<Order>>(tab === "orders" && can("commerce.orders.view") && access.capabilities.payments ? "/orders/inbox" : null, { environment, to, limit: 25, cursor: cursors.at(-1) });
  const collections = useCommerceQuery<{ collections: Collection[] }>(tab === "products" && mode === "collections" && access.capabilities.collections ? "/collections" : null, { archived: false });
  const [selectedCollections, setSelectedCollections] = useState<string[]>(preselectedCollectionIds), [collectionProducts, setCollectionProducts] = useState<Record<string, Product[]>>({}), [selectedByCollection, setSelectedByCollection] = useState<Record<string, string[]>>({});
  const [collectionLoading, setCollectionLoading] = useState(false), [collectionError, setCollectionError] = useState("");
  const selectionKey = JSON.stringify(selectedCollections);
  useEffect(() => { let active = true; if (!selectedCollections.length) { setCollectionProducts({}); return; } setCollectionLoading(true); setCollectionError("");
    Promise.all(selectedCollections.map(async (id) => ({ id, response: await request<{ products: Product[] }>(`/collections/${id}/products`, { params: { limit: 100 } }) })))
      .then((rows) => { if (!active) return; setCollectionProducts(Object.fromEntries(rows.map((row) => [row.id, row.response.products]))); setSelectedByCollection((old) => { const next = { ...old }; rows.forEach((row) => { if (!next[row.id]) next[row.id] = row.response.products.filter(eligible).map((p) => p.id); }); return next; }); })
      .catch(() => active && setCollectionError("Collection products could not be loaded.")).finally(() => active && setCollectionLoading(false)); return () => { active = false; };
  }, [request, selectionKey]);
  const chosen = useMemo(() => { const seen = new Set<string>(); let duplicates = 0; const sections = selectedCollections.map((collectionId) => ({ collectionId, productIds: (selectedByCollection[collectionId] || []).filter((id) => { if (seen.has(id)) { duplicates += 1; return false; } seen.add(id); return true; }) })).filter((section) => section.productIds.length); return { sections, count: seen.size, duplicates }; }, [selectedCollections, selectedByCollection]);
  const intent = useRef<{ fingerprint: string; idempotencyKey: string } | null>(null), [uncertain, setUncertain] = useState(false), busy = !!disabled || action.busy || uncertain;
  function send(input: Record<string, unknown>) { const fingerprint = JSON.stringify({ ...input, to }); if (intent.current?.fingerprint !== fingerprint) intent.current = { fingerprint, idempotencyKey: crypto.randomUUID() }; setUncertain(true); setNotice("Delivery is being checked. Inspect the inbox before sending again."); void action.run<{ message: { status: string } }>("/messages", { ...input, to, idempotencyKey: intent.current.idempotencyKey }, (result) => { setNotice(result.message.status === "unknown" ? "Delivery is unknown. Check the inbox before sending again." : "Message submitted to WhatsApp."); onSent(); }); }
  if (!can("commerce.messages.send") || !can("inbox.reply")) return <p>This workspace role cannot send Commerce messages.</p>;
  if (!access.capabilities.catalog) return <p>Commerce catalog is not enabled.</p>;
  return <div className="space-y-4"><p className="text-sm">Customer: {to}. Sending requires an open WhatsApp customer service window.</p><EnvironmentPicker /><div className="flex gap-2"><Button variant={tab === "products" ? "primary" : "outline"} size="sm" onClick={() => { setTab("products"); setCursors([]); }}>Catalog</Button><Button variant={tab === "orders" ? "primary" : "outline"} size="sm" onClick={() => { setTab("orders"); setCursors([]); }}>Customer orders</Button></div><ErrorNotice message={action.error} />{notice && <p role="status" className="rounded-md bg-blue-50 p-3 text-sm">{notice}</p>}
    {tab === "products" ? <><div className="flex flex-wrap gap-2"><Button disabled={busy} variant="outline" onClick={() => send({ kind: "catalog" })}>Send catalog</Button>{access.capabilities.collections && <><Button size="sm" variant={mode === "custom" ? "primary" : "outline"} onClick={() => setMode("custom")}>Custom products</Button><Button size="sm" variant={mode === "collections" ? "primary" : "outline"} onClick={() => setMode("collections")}>Collections</Button></>}</div>
      {mode === "custom" ? <><QueryState {...products} empty={!products.data?.products.length} />{products.data?.products.map((p) => <Check key={p.id} label={`${p.name} · ${money(p.pricePaise)} · ${p.syncStatus}`} checked={selected.includes(p.id)} disabled={busy || !eligible(p) || selected.length >= 30 && !selected.includes(p.id)} onChange={(v) => setSelected((old) => v ? [...old, p.id] : old.filter((id) => id !== p.id))} />)}<Button disabled={busy || !selected.length} onClick={() => send({ kind: selected.length === 1 ? "product" : "product_list", productIds: selected })}>Send {selected.length} selected product{selected.length === 1 ? "" : "s"}</Button><Pager next={products.data?.nextCursor} back={cursors.length ? () => setCursors((v) => v.slice(0, -1)) : undefined} onNext={() => setCursors((v) => [...v, products.data!.nextCursor!])} /></>
      : <><QueryState {...collections} empty={!collections.data?.collections.length} />{collections.data?.collections.map((c) => <Check key={c.id} label={`${c.name} · ${c.eligibleProducts} eligible`} checked={selectedCollections.includes(c.id)} disabled={busy || selectedCollections.length >= 10 && !selectedCollections.includes(c.id)} onChange={(v) => setSelectedCollections((old) => v ? [...old, c.id] : old.filter((id) => id !== c.id))} />)}{collectionLoading && <p role="status">Loading collection products…</p>}<ErrorNotice message={collectionError} />{chosen.duplicates > 0 && <p className="rounded bg-amber-50 p-2 text-sm text-amber-800">{chosen.duplicates} duplicate product{chosen.duplicates === 1 ? " was" : "s were"} removed from later sections.</p>}{selectedCollections.map((id) => <div key={id} className="space-y-2 rounded border p-3"><p className="font-semibold">{collections.data?.collections.find((c) => c.id === id)?.name || "Collection"}</p>{(collectionProducts[id] || []).map((p) => <Check key={p.id} label={`${p.name} · ${p.metaReviewStatus} · ${p.syncStatus}`} checked={(selectedByCollection[id] || []).includes(p.id)} disabled={busy || !eligible(p)} onChange={(v) => setSelectedByCollection((old) => ({ ...old, [id]: v ? [...(old[id] || []), p.id] : (old[id] || []).filter((productId) => productId !== p.id) }))} />)}</div>)}<p className="text-sm font-semibold">{chosen.count}/30 products selected · {selectedCollections.length}/10 sections</p><Button disabled={busy || collectionLoading || !chosen.count || chosen.count > 30} onClick={() => send({ kind: "product_list", sections: chosen.sections })}>Send selected collections</Button></>}</>
    : <>{!access.capabilities.payments && <p className="text-sm">Payment operations are not enabled yet.</p>}<QueryState {...orders} empty={!orders.data?.items.length} />{orders.data?.items.map((order) => <PaymentAction key={order.id} order={order} busy={busy} send={send} />)}<Pager next={orders.data?.nextCursor} back={cursors.length ? () => setCursors((v) => v.slice(0, -1)) : undefined} onNext={() => setCursors((v) => [...v, orders.data!.nextCursor!])} /></>}
  </div>;
}
export default function InboxCommerce(props: Props) { const workspaceId = useWorkspaceId(); return <CommerceProvider key={`${workspaceId}:${props.to}`} workspaceId={workspaceId}><InboxActions {...props} /></CommerceProvider>; }
