export type Environment = "test" | "live";
export type Page<T> = { items: T[]; nextCursor: string | null };
export type Access = { workspaceId: string; permissions: string[]; capabilities: Record<"catalog" | "orders" | "payments" | "checkout" | "gateway" | "oauth" | "native", boolean> & { delivery?: boolean } };
export type Product = { id: string; sku: string; name: string; description: string; imageUrl: string; productUrl: string; brand: string; category: string;
  condition: "new" | "refurbished" | "used"; pricePaise: number; taxRateBps: number | null; taxConfirmed: boolean; available: boolean;
  trackInventory: boolean; stockOnHand: number; stockReserved: number; archivedAt: string | null; revision: number; syncedRevision: number; syncStatus: string; syncError: string };
export type Catalog = { id: string; catalogId: string; wabaId: string; phoneNumberId: string; revision: number; status: string;
  catalogVisible: boolean; cartEnabled: boolean; activePhoneMatches?: boolean; lastError: string; lastCheckedAt: string | null };
export type Gateway = { id: string; environment: Environment; authType: "api_keys" | "oauth"; status: string; active: boolean; revision: number;
  keyLabel: string; identityVerified: boolean; merchantAccountId?: string; webhookStatus: string; nativePaymentStatus: string;
  tokenExpiresAt?: string; lastErrorCode: string; nativeConfigurationName?: string };
export type DeliveryLocation = { latitude: number; longitude: number; source: "gps" | "map" | "manual"; accuracy?: number | null; confirmed: boolean };
export type Address = { name: string; phone: string; line1: string; line2?: string; city: string; state: string; postalCode: string; country: "IN"; location?: DeliveryLocation };
export type OrderItem = { productId: string; sku: string; name: string; quantity: number; unitPricePaise: number; productRevision: number; grossPaise: number; includedTaxPaise: number | null; taxRateBps: number | null };
export type Order = { id: string; manualDeliveryId?: string | null; orderNumber: string; environment: Environment; status: string; paymentStatus: string; customerName: string;
  customerPhone: string; receivedAt: string; items: OrderItem[]; sourceItems: { sku: string; quantity: number; unitPricePaise: number }[];
  totalPaise: number; subtotalPaise: number; deliveryPaise: number; includedTaxPaise: number | null; deliveryTaxRateBps: number | null;
  fulfillmentMethod: "" | "pickup" | "delivery"; address: Address | null; customerNote: string; warnings: string[]; revision: number;
  reviewedAt: string | null; activeAttemptId: string | null; paidAttemptId: string | null; attentionReason: string; wabaId: string; phoneNumberId: string };
export type Quote = { items: OrderItem[]; totalPaise: number; subtotalPaise: number; deliveryPaise: number; includedTaxPaise: number | null;
  warnings: string[]; blockers: string[]; productRevisions: { productId: string; revision: number }[] };
export type Attempt = { id: string; orderId: string; gatewayConnectionId: string; environment: Environment; status: string; amountPaise: number;
  paymentUrl: string; expiresAt: string; active: boolean; lastError: string; reference: string; mode: "razorpay_payment_link" | "whatsapp_native" };
export type Payment = { id: string; orderId: string; providerPaymentId: string; environment: Environment; amountPaise: number; refundedPaise: number;
  method: string; status: string; overpayment: boolean; verifiedAt: string; lastError: string };
export type Refund = { id: string; providerRefundId: string; amountPaise: number; status: string; verifiedAt: string };
export type EventRecord = { id: string; status: string; attempts: number; lastError: string; createdAt: string };
export type Notification = { id: string; status: string; whatsappMessageId: string; lastError: string };
export type OrderSettings = { revision: number; enabled: boolean; pickupEnabled: boolean; deliveryEnabled: boolean; pickupInstructions: string; testRecipients: string[] };
export type PaymentSettings = { revision: number; liveCheckoutEnabled: boolean; reservationMinutes: number; checkoutEnabled: boolean; liveEnabled: boolean };
