import { Eye, FileText, LayoutDashboard, Megaphone, Send, TrendingDown, TrendingUp, Users } from "lucide-react";
import { Card } from "@components/ui/Card";
import { cn } from "@shared/utils/cn";

export function DashboardSummaryCards({ analytics, deliveryRatePct, readRatePct, sent, delivered, read, monthly, monthlyUp, contactsGrowth, contactsUp }: any) {
  return (
    <div className="grid gap-4 lg:grid-cols-3">
      <Card className="p-6 rounded-[5px]"><div className="flex items-center gap-4"><div className="size-12 rounded-[10px] bg-emerald-50 text-emerald-700 flex items-center justify-center"><Send size={20} /></div><div className="text-sm font-black text-slate-800">Delivery Rate</div></div><div className="mt-6 text-4xl font-black tracking-tight text-slate-900">{deliveryRatePct.toFixed(1)}%</div><div className="mt-4 h-2 rounded-full bg-slate-200 overflow-hidden"><div className="h-full bg-emerald-600" style={{ width: `${Math.min(100, Math.max(0, deliveryRatePct))}%` }} /></div><div className="mt-3 text-sm text-slate-500 font-medium">{delivered.toLocaleString()} of {sent.toLocaleString()} messages</div></Card>
      <Card className="p-6 rounded-[5px]"><div className="flex items-center gap-4"><div className="size-12 rounded-[10px] bg-violet-50 text-violet-700 flex items-center justify-center"><Eye size={20} /></div><div className="text-sm font-black text-slate-800">Read Rate</div></div><div className="mt-6 text-4xl font-black tracking-tight text-slate-900">{readRatePct.toFixed(1)}%</div><div className="mt-4 h-2 rounded-full bg-slate-200 overflow-hidden"><div className="h-full bg-violet-600" style={{ width: `${Math.min(100, Math.max(0, readRatePct))}%` }} /></div><div className="mt-3 text-sm text-slate-500 font-medium">{read.toLocaleString()} of {sent.toLocaleString()} messages</div></Card>
      <Card className="p-6 rounded-[5px]"><div className="flex items-center gap-4"><div className="size-12 rounded-[10px] bg-amber-50 text-amber-700 flex items-center justify-center"><TrendingUp size={20} /></div><div className="text-sm font-black text-slate-800">Monthly Growth</div></div><div className="mt-6 flex items-end gap-3"><div className="text-4xl font-black tracking-tight text-slate-900">{Math.abs(Number(monthly.pct || 0)).toFixed(1)}%</div><div className={cn("mb-1 inline-flex items-center gap-1 text-sm font-black", monthlyUp ? "text-emerald-600" : "text-red-600")}>{monthlyUp ? <TrendingUp size={18} /> : <TrendingDown size={18} />}</div></div><div className="mt-3 text-sm text-slate-500 font-medium">{Number(monthly.thisMonth || 0).toLocaleString()} this month vs {Number(monthly.lastMonth || 0).toLocaleString()} last month</div></Card>
      <Card className="p-6 rounded-[5px] lg:col-span-1"><div className="flex items-center gap-3"><div className="size-12 rounded-[10px] bg-blue-50 text-blue-700 flex items-center justify-center"><Users size={20} /></div><div className="min-w-0 flex-1"><div className="text-lg font-black text-slate-900">Contact Growth</div><div className="text-xs font-bold text-slate-500">This week</div></div></div><div className="mt-5 flex items-end justify-between"><div className="text-4xl font-black text-slate-900">{Number(contactsGrowth.thisWeek || 0).toLocaleString()}</div><div className={cn("flex items-center gap-1 text-sm font-black", contactsUp ? "text-emerald-600" : "text-red-600")}>{contactsUp ? <TrendingUp size={18} /> : <TrendingDown size={18} />}{Math.abs(Number(contactsGrowth.pct || 0)).toFixed(1)}%</div></div></Card>
      <Card className="p-6 rounded-[5px] lg:col-span-2"><div className="flex items-center gap-3"><div className="size-12 rounded-[10px] bg-fuchsia-50 text-fuchsia-700 flex items-center justify-center"><LayoutDashboard size={20} /></div><div className="text-lg font-black text-slate-900">Campaign Overview</div></div><div className="mt-6 grid grid-cols-2 gap-6"><div className="flex items-center gap-4"><div className="size-14 rounded-full bg-fuchsia-50 flex items-center justify-center text-fuchsia-700"><Megaphone size={22} /></div><div><div className="text-4xl font-black text-slate-900">{Number(analytics?.counts?.campaigns || 0).toLocaleString()}</div><div className="text-sm font-medium text-slate-500">Campaigns</div></div></div><div className="flex items-center gap-4"><div className="size-14 rounded-full bg-violet-50 flex items-center justify-center text-violet-700"><FileText size={22} /></div><div><div className="text-4xl font-black text-slate-900">{Number(analytics?.counts?.templates || 0).toLocaleString()}</div><div className="text-sm font-medium text-slate-500">Templates</div></div></div></div></Card>
    </div>
  );
}
