import { Eye, FileText, IndianRupee, LayoutDashboard, Megaphone, MousePointerClick, TrendingDown, TrendingUp, Users } from "lucide-react";
import { Card } from "@components/ui/Card";
import { formatCurrencySafe } from "@shared/config/currency";
import { cn } from "@shared/utils/cn";

export function DashboardSummaryCards({ analytics, deliveryRatePct, readRatePct, sent, delivered, read, monthly, monthlyUp, contactsGrowth, contactsUp }: any) {
  const clicked = Number(analytics?.overview?.clicked || 0);
  const converted = Number(analytics?.overview?.converted || 0);
  const revenue = Number(analytics?.overview?.revenue || 0);
  const spend = Number(analytics?.overview?.spend || 0);
  const roi = analytics?.overview?.roi;
  const clickRatePct = Number(analytics?.rates?.clickRatePct || 0);
  const conversionRatePct = Number(analytics?.rates?.conversionRatePct || 0);

  return (
    <div className="grid gap-4 lg:grid-cols-3">
      <Card className="p-6 rounded-[5px]"><div className="flex items-center gap-4"><div className="size-12 rounded-[10px] bg-emerald-50 text-emerald-700 flex items-center justify-center"><MousePointerClick size={20} /></div><div className="text-sm font-black text-slate-800">Click Through Rate</div></div><div className="mt-6 text-4xl font-black tracking-tight text-slate-900">{clickRatePct.toFixed(1)}%</div><div className="mt-4 h-2 rounded-full bg-slate-200 overflow-hidden"><div className="h-full bg-emerald-600" style={{ width: `${Math.min(100, Math.max(0, clickRatePct))}%` }} /></div><div className="mt-3 text-sm text-slate-500 font-medium">{clicked.toLocaleString()} of {sent.toLocaleString()} messages clicked</div></Card>
      <Card className="p-6 rounded-[5px]"><div className="flex items-center gap-4"><div className="size-12 rounded-[10px] bg-violet-50 text-violet-700 flex items-center justify-center"><Eye size={20} /></div><div className="text-sm font-black text-slate-800">Read Rate</div></div><div className="mt-6 text-4xl font-black tracking-tight text-slate-900">{readRatePct.toFixed(1)}%</div><div className="mt-4 h-2 rounded-full bg-slate-200 overflow-hidden"><div className="h-full bg-violet-600" style={{ width: `${Math.min(100, Math.max(0, readRatePct))}%` }} /></div><div className="mt-3 text-sm text-slate-500 font-medium">{read.toLocaleString()} of {sent.toLocaleString()} messages</div></Card>
      <Card className="p-6 rounded-[5px]"><div className="flex items-center gap-4"><div className="size-12 rounded-[10px] bg-amber-50 text-amber-700 flex items-center justify-center"><TrendingUp size={20} /></div><div className="text-sm font-black text-slate-800">Conversion Rate</div></div><div className="mt-6 flex items-end gap-3"><div className="text-4xl font-black tracking-tight text-slate-900">{conversionRatePct.toFixed(1)}%</div><div className={cn("mb-1 inline-flex items-center gap-1 text-sm font-black", converted > 0 ? "text-emerald-600" : "text-slate-400")}>{converted > 0 ? <TrendingUp size={18} /> : <TrendingDown size={18} />}</div></div><div className="mt-3 text-sm text-slate-500 font-medium">{converted.toLocaleString()} conversions from {clicked.toLocaleString()} clicks</div></Card>
      <Card className="p-6 rounded-[5px] lg:col-span-1"><div className="flex items-center gap-3"><div className="size-12 rounded-[10px] bg-blue-50 text-blue-700 flex items-center justify-center"><Users size={20} /></div><div className="min-w-0 flex-1"><div className="text-lg font-black text-slate-900">Contact Growth</div><div className="text-xs font-bold text-slate-500">This week</div></div></div><div className="mt-5 flex items-end justify-between"><div className="text-4xl font-black text-slate-900">{Number(contactsGrowth.thisWeek || 0).toLocaleString()}</div><div className={cn("flex items-center gap-1 text-sm font-black", contactsUp ? "text-emerald-600" : "text-red-600")}>{contactsUp ? <TrendingUp size={18} /> : <TrendingDown size={18} />}{Math.abs(Number(contactsGrowth.pct || 0)).toFixed(1)}%</div></div></Card>
      <Card className="p-6 rounded-[5px] lg:col-span-2"><div className="flex items-center gap-3"><div className="size-12 rounded-[10px] bg-fuchsia-50 text-fuchsia-700 flex items-center justify-center"><LayoutDashboard size={20} /></div><div className="text-lg font-black text-slate-900">Revenue Attribution</div></div><div className="mt-6 grid grid-cols-1 gap-6 md:grid-cols-3"><div className="flex items-center gap-4"><div className="size-14 rounded-full bg-fuchsia-50 flex items-center justify-center text-fuchsia-700"><IndianRupee size={22} /></div><div><div className="text-3xl font-black text-slate-900">{formatCurrencySafe(Math.round(revenue), "₹")}</div><div className="text-sm font-medium text-slate-500">Revenue</div></div></div><div className="flex items-center gap-4"><div className="size-14 rounded-full bg-violet-50 flex items-center justify-center text-violet-700"><Megaphone size={22} /></div><div><div className="text-3xl font-black text-slate-900">{formatCurrencySafe(Math.round(spend), "₹")}</div><div className="text-sm font-medium text-slate-500">Spend</div></div></div><div className="flex items-center gap-4"><div className="size-14 rounded-full bg-sky-50 flex items-center justify-center text-sky-700"><TrendingUp size={22} /></div><div><div className="text-3xl font-black text-slate-900">{roi === null || roi === undefined ? "--" : `${(Number(roi) * 100).toFixed(0)}%`}</div><div className="text-sm font-medium text-slate-500">ROI</div></div></div></div><div className="mt-5 grid grid-cols-2 gap-6 border-t border-slate-100 pt-5"><div className="flex items-center gap-4"><div className="size-14 rounded-full bg-fuchsia-50 flex items-center justify-center text-fuchsia-700"><Megaphone size={22} /></div><div><div className="text-4xl font-black text-slate-900">{Number(analytics?.counts?.campaigns || 0).toLocaleString()}</div><div className="text-sm font-medium text-slate-500">Campaigns</div></div></div><div className="flex items-center gap-4"><div className="size-14 rounded-full bg-violet-50 flex items-center justify-center text-violet-700"><FileText size={22} /></div><div><div className="text-4xl font-black text-slate-900">{Number(analytics?.counts?.templates || 0).toLocaleString()}</div><div className="text-sm font-medium text-slate-500">Templates</div></div></div></div></Card>
    </div>
  );
}
