import type { AxiosInstance } from "axios";

export const api: AxiosInstance;
export function getToken(): string;
export function getWorkspaceId(): string;
export function setWorkspaceId(workspaceId: string): void;
export function setToken(token: string): void;

// Keep responses loosely typed; the UI can narrow as needed.
export const API: {
  baseUrl: string;
  auth: {
    register(payload: any): Promise<any>;
    login(payload: any): Promise<any>;
    verifyLoginOtp(payload: any): Promise<any>;
    resendLoginOtp(payload: any): Promise<any>;
    verifyRegisterOtp(payload: any): Promise<any>;
    resendRegisterOtp(payload: any): Promise<any>;
    forgotPassword(payload: any): Promise<any>;
    resetPassword(payload: any): Promise<any>;
    adminForgotPassword(payload: any): Promise<any>;
    adminResetPassword(payload: any): Promise<any>;
    me(): Promise<any>;
    apiKeyStatus(): Promise<any>;
    listApiKeys(): Promise<any>;
    generateApiKey(payload?: any): Promise<any>;
    regenerateApiKey(payload?: any): Promise<any>;
    deleteApiKey(id: string): Promise<any>;
    requestApiKeyOtp(payload: any): Promise<any>;
    verifyApiKeyOtp(payload: any): Promise<any>;
    updateProfile(payload: any): Promise<any>;
    requestProfileOtp(payload: any): Promise<any>;
    verifyProfileOtp(payload: any): Promise<any>;
    changePassword(payload: any): Promise<any>;
    requestEnable2fa(): Promise<any>;
    verifyEnable2fa(payload: any): Promise<any>;
    disable2fa(): Promise<any>;
    logout(): Promise<any>;
  };
  admin: {
    overview(params?: any): Promise<any>;
    users(params?: any): Promise<any>;
    updateUserStatus(id: string, payload: any): Promise<any>;
    userApiKeys(id: string): Promise<any>;
    sendChatAccessOtp(id: string): Promise<any>;
    verifyChatAccessOtp(id: string, payload: any): Promise<any>;
    enableChatAccess(id: string): Promise<any>;
    disableChatAccess(id: string): Promise<any>;
    enableCampaignSendAccess(id: string): Promise<any>;
    disableCampaignSendAccess(id: string): Promise<any>;
    disableUserApiKey(id: string, keyId: string): Promise<any>;
    enableUserApiKey(id: string, keyId: string): Promise<any>;
    blockUser(id: string): Promise<any>;
    unblockUser(id: string): Promise<any>;
    channels(params?: any): Promise<any>;
    workspaces(params?: any): Promise<any>;
    masterCampaigns(params?: any): Promise<any>;
    masterTemplates(params?: any): Promise<any>;
    masterTemplateGet(id: string): Promise<any>;
    masterTemplateUpdate(id: string, payload: any): Promise<any>;
    masterTemplateDelete(id: string): Promise<any>;
    masterTemplateSyncStatus(id: string): Promise<any>;
    masterTemplateSyncMeta(payload: any): Promise<any>;
    masterContacts(params?: any): Promise<any>;
    notifications(params?: any): Promise<any>;
    subscriptionPlans(): Promise<any>;
    subscriptionsData(params?: any): Promise<any>;
    subscriptionWorkspaceOverview(workspaceId: string): Promise<any>;
    subscriptionWorkspaceHistory(workspaceId: string, params?: any): Promise<any>;
    subscriptionWorkspacePaymentLinks(workspaceId: string, params?: any): Promise<any>;
    assignWorkspacePlan(workspaceId: string, payload: any): Promise<any>;
    disableActiveWorkspacePlan(workspaceId: string): Promise<any>;
    createWorkspacePaymentLink(workspaceId: string, payload: any): Promise<any>;
    cancelWorkspacePaymentLink(id: string): Promise<any>;
    transactionsLogs(params?: any): Promise<any>;
    messageLogs(params?: any): Promise<any>;
    paymentGateway(params?: any): Promise<any>;
    supportTickets(params?: any): Promise<any>;
    resolveSupportTicket(id: string, payload?: any): Promise<any>;
    appUpdate(): Promise<any>;
    changePassword(payload: any): Promise<any>;

    profile(): Promise<any>;
    profileUpdate(payload: any): Promise<any>;
    profileLogins(params?: any): Promise<any>;
    profileRequests(params?: any): Promise<any>;
    createProfileRequest(payload: any): Promise<any>;
    verifyProfileRequestOtp(requestId: string, payload: any): Promise<any>;
    resendProfileRequestOtp(requestId: string): Promise<any>;

    pages(): Promise<any>;
    pageGet(slug: string): Promise<any>;
    pageUpsert(slug: string, payload: any): Promise<any>;
    platformBrandGet(): Promise<any>;
    platformBrandUpdate(payload: any): Promise<any>;
    platformBrandUploadLogo(file: any, onProgress?: (pct: number) => void): Promise<any>;
    careerApplications(params?: any): Promise<any>;
    updateCareerApplication(id: string, payload: any): Promise<any>;
    downloadCareerResume(id: string): Promise<Blob>;

    crmWorkspace(workspaceId: string): Promise<any>;
    crmSetEnabled(workspaceId: string, enabled: boolean): Promise<any>;
    crmSetLeadWindowHours(workspaceId: string, leadWindowHours: number): Promise<any>;
    crmEmployees(workspaceId: string): Promise<any>;
    crmCreateEmployee(workspaceId: string, payload: any): Promise<any>;

    getWorkspaceExternalChatFeature(workspaceId: string): Promise<any>;
    setWorkspaceExternalChatFeature(workspaceId: string, enabled: boolean): Promise<any>;
    setApiKeyChatAccess(userId: string, keyId: string, enabled: boolean): Promise<any>;
    syncApiKeysChatAccess(userId: string, enabled: boolean): Promise<any>;
    docsList(params?: any): Promise<any>;
    docsGet(id: string): Promise<any>;
    docsCreate(payload: any): Promise<any>;
    docsUpdate(id: string, payload: any): Promise<any>;
    docsDelete(id: string): Promise<any>;
    docsBrandGet(): Promise<any>;
    docsBrandUpdate(payload: any): Promise<any>;
    docsBrandUploadLogo(file: any, onProgress?: (pct: number) => void): Promise<any>;
  };
  superAdmin: {
    profile(): Promise<any>;
    updateProfileName(payload: any): Promise<any>;
    changeProfilePassword(payload: any): Promise<any>;
    requestProfileOtp(payload: any): Promise<any>;
    verifyProfileOtp(payload: any): Promise<any>;
    setProfile2fa(payload: any): Promise<any>;
    admins(params?: any): Promise<any>;
    adminDetail(id: string): Promise<any>;
    updateAdmin(id: string, payload: any): Promise<any>;
    decideAdminProfileRequest(adminId: string, requestId: string, payload: any): Promise<any>;
    assignAdmin(payload: any): Promise<any>;
    removeAdmin(payload: any): Promise<any>;
    suspendUser(payload: any): Promise<any>;
    resetUserPassword(payload: any): Promise<any>;
    securityLogs(params?: any): Promise<any>;
    platformSettings(): Promise<any>;
    platformSettingsByCategory(category: string): Promise<any>;
    updatePlatformSetting(key: string, payload: any): Promise<any>;
    bulkUpdatePlatformSettings(payload: any): Promise<any>;
    testPlatformCategory(category: string, payload?: any): Promise<any>;
    platformAddons(): Promise<any>;
    platformAddonsByCategory(category: string): Promise<any>;
    updatePlatformAddon(key: string, payload: any): Promise<any>;
    bulkUpdatePlatformAddons(payload: any): Promise<any>;
    billingPlans(params?: any): Promise<any>;
    billingPlanGet(id: string): Promise<any>;
    billingPlanCreate(payload: any): Promise<any>;
    billingPlanUpdate(id: string, payload: any): Promise<any>;
    billingPlanReview(id: string, payload?: any): Promise<any>;
    billingPlanPublish(id: string, payload?: any): Promise<any>;
    billingPlanDisable(id: string): Promise<any>;
    billingPlanArchive(id: string): Promise<any>;
    billingPlanDelete(id: string): Promise<any>;
    billingSettingsGet(): Promise<any>;
    billingSettingsUpdate(payload: any): Promise<any>;
    billingPricePreview(payload: any): Promise<any>;
  };
  crm: {
    workspace(): Promise<any>;
    dashboard(): Promise<any>;
    setLeadWindowHours(leadWindowHours: number): Promise<any>;
    setAssignmentLockMinutes(assignmentLockMinutes: number): Promise<any>;
    setAssignmentMode(payload: any): Promise<any>;
    setAssignmentSchedule(payload: any): Promise<any>;
    employees(): Promise<any>;
    createEmployee(payload: any): Promise<any>;
    updateEmployeeStatus(employeeId: string, status: string): Promise<any>;
    employeeProfile(employeeId: string): Promise<any>;
    updateEmployeeProfile(employeeId: string, payload: any): Promise<any>;
    employeeLeads(employeeId: string, params?: any): Promise<any>;
    employeeActivities(employeeId: string, params?: any): Promise<any>;
    employeeSessions(employeeId: string, params?: any): Promise<any>;
    employeeRequests(params?: any): Promise<any>;
    decideEmployeeRequest(requestId: string, payload: any): Promise<any>;
    verifyEmployeeEmailOtp(employeeId: string, payload: any): Promise<any>;
    sendEmployeeResetLink(employeeId: string): Promise<any>;
    resetEmployeePassword(employeeId: string, payload: any): Promise<any>;
    manualAssignLead(phone: string, payload: any): Promise<any>;
    conversationEvents(phone: string, params?: any): Promise<any>;
  };
  public: {
    page(slug: string): Promise<any>;
    platformBrandGet(): Promise<any>;
    createSupportTicket(payload: any): Promise<any>;
    applyCareer(payload: any, file: any, onProgress?: (pct: number) => void): Promise<any>;
  };
  workspaces: {
    list(): Promise<any>;
    create(payload: any): Promise<any>;
  };
  credentials: {
    getWhatsApp(): Promise<any>;
    upsertWhatsApp(payload: any): Promise<any>;
    deleteWhatsApp(): Promise<any>;
  };
  templates: {
    list(params?: any): Promise<any>;
    create(payload: any): Promise<any>;
    get(id: string): Promise<any>;
    update(id: string, payload: any): Promise<any>;
    remove(id: string): Promise<any>;
    submit(id: string): Promise<any>;
    status(id: string): Promise<any>;
    syncMeta(payload?: any): Promise<any>;
    uploadMedia(file: any, onProgress?: (pct: number) => void): Promise<any>;
    downloadMediaByHandle(handle: string): Promise<any>;
  };
  messages: {
    send(payload: any): Promise<any>;
    sendText(payload: any): Promise<any>;
    sendMedia(payload: any): Promise<any>;
    bulk(payload: any): Promise<any>;
    logs(params?: any): Promise<any>;
    status(waId: string): Promise<any>;
    byPhone(phone: string, params?: any): Promise<any>;
    downloadMedia(id: string): Promise<any>;
    uploadMedia(file: any, onProgress?: (pct: number) => void): Promise<any>;
  };
  analytics: {
    overview(params?: any): Promise<any>;
    template(id: string): Promise<any>;
  };
  meta: {
    status(): Promise<any>;
    subscriptionHealth(): Promise<any>;
    save(payload: any): Promise<any>;
    updateProfile(payload: any): Promise<any>;
    uploadProfilePicture(file: any): Promise<any>;
    listFlows(params?: any): Promise<any>;
    createFlow(payload: any): Promise<any>;
    uploadFlowJson(flowId: string, flowJson: any): Promise<any>;
    publishFlow(flowId: string): Promise<any>;
  };
  links: {
    create(payload: any): Promise<any>;
    tracked: {
      list(): Promise<any>;
      create(payload: any): Promise<any>;
      update(id: string, payload: any): Promise<any>;
      remove(id: string): Promise<any>;
      analytics(id: string, params?: any): Promise<any>;
      qrSvgUrl(id: string): string;
      qrPngUrl(id: string): string;
    };
  };
  billing: {
    plans(): Promise<any>;
    current(): Promise<any>;
    history(params?: any): Promise<any>;
  };
  wallet: {
    get(): Promise<any>;
    createRechargeOrder(payload: any): Promise<any>;
    history(params?: any): Promise<any>;
  };
  campaigns: {
    list(params?: any): Promise<any>;
    get(id: string): Promise<any>;
    estimate(payload: any): Promise<any>;
    metrics(id: string): Promise<any>;
    messages(id: string, params?: any): Promise<any>;
    replies(id: string, params?: any): Promise<any>;
    creditUsage(id: string): Promise<any>;
    failedRecipients(id: string): Promise<any>;
    retryFailed(id: string): Promise<any>;
    remove(id: string, params?: { force?: boolean }): Promise<any>;
    action(id: string, action: "pause" | "resume" | "stop" | "complete"): Promise<any>;
    create(payload: any): Promise<any>;
  };
  reports: {
    apiCampaigns(params?: any): Promise<any>;
    apiCampaign(id: string): Promise<any>;
    apiMessages(params?: any): Promise<any>;
    apiMessage(id: string): Promise<any>;
  };
  conversations: {
    clear(phone: string): Promise<any>;
    list(params?: any): Promise<any>;
    get(phone: string): Promise<any>;
    read(phone: string): Promise<any>;
  };
  contacts: {
    list(params?: any): Promise<any>;
    get(id: string): Promise<any>;
    lookupByPhone(phone: string): Promise<any>;
    create(payload: any): Promise<any>;
    update(id: string, payload: any): Promise<any>;
    remove(id: string): Promise<any>;
    exportCsv(contactIds: string[]): Promise<any>;
  };
  automation: {
    triggerEvent(payload: any): Promise<any>;
  };
};
