export function buildApiGroupPrimary(api, unwrap) {
  return {
    auth: {
      register: (payload) => api.post("/auth/register", payload).then(unwrap),
      login: (payload) => api.post("/auth/login", payload, { timeout: 60000 }).then(unwrap),
      verifyLoginOtp: (payload) => api.post("/auth/login/verify-otp", payload).then(unwrap),
      resendLoginOtp: (payload) => api.post("/auth/login/resend-otp", payload).then(unwrap),
      verifyRegisterOtp: (payload) => api.post("/auth/register/verify-otp", payload).then(unwrap),
      resendRegisterOtp: (payload) => api.post("/auth/register/resend-otp", payload).then(unwrap),
      forgotPassword: (payload) => api.post("/auth/forgot-password", payload).then(unwrap),
      resetPassword: (payload) => api.post("/auth/reset-password", payload).then(unwrap),
      adminForgotPassword: (payload) => api.post("/auth/admin/forgot-password", payload).then(unwrap),
      adminResetPassword: (payload) => api.post("/auth/admin/reset-password", payload).then(unwrap),
      me: () => api.get("/auth/me").then(unwrap),
      apiKeyStatus: () => api.get("/auth/api-key").then(unwrap),
      listApiKeys: () => api.get("/api-keys").then(unwrap),
      generateApiKey: (payload) => api.post("/api-keys/generate", payload || {}).then(unwrap),
      regenerateApiKey: (payload) => api.post("/api-keys/regenerate", payload || {}).then(unwrap),
      deleteApiKey: (id) => api.delete(`/api-keys/${encodeURIComponent(id)}`).then(unwrap),
      requestApiKeyOtp: (payload) => api.post("/auth/api-key/request-otp", payload).then(unwrap),
      verifyApiKeyOtp: (payload) => api.post("/auth/api-key/verify-otp", payload).then(unwrap),
      updateProfile: (payload) => api.put("/auth/profile", payload).then(unwrap),
      requestProfileOtp: (payload) => api.post("/auth/profile/request-otp", payload).then(unwrap),
      verifyProfileOtp: (payload) => api.post("/auth/profile/verify-otp", payload).then(unwrap),
      changePassword: (payload) => api.post("/auth/change-password", payload).then(unwrap),
      requestEnable2fa: () => api.post("/auth/2fa/request-enable").then(unwrap),
      verifyEnable2fa: (payload) => api.post("/auth/2fa/verify-enable", payload).then(unwrap),
      disable2fa: () => api.post("/auth/2fa/disable").then(unwrap),
      logout: () => api.post("/auth/logout").then(unwrap),
    },
    crm: {
      workspace: () => api.get("/crm/workspace").then(unwrap),
      dashboard: () => api.get("/crm/dashboard").then(unwrap),
      setLeadWindowHours: (leadWindowHours) => api.put("/crm/settings/lead-window", { leadWindowHours }).then(unwrap),
      setAssignmentLockMinutes: (assignmentLockMinutes) => api.put("/crm/settings/assignment-lock", { assignmentLockMinutes }).then(unwrap),
      setAssignmentMode: (payload) => api.put("/crm/settings/assignment-mode", payload || {}).then(unwrap),
      setAssignmentSchedule: (payload) => api.put("/crm/settings/assignment-schedule", payload || {}).then(unwrap),
      employees: () => api.get("/crm/employees").then(unwrap),
      createEmployee: (payload) => api.post("/crm/employees", payload).then(unwrap),
      updateEmployeeStatus: (employeeId, status) => api.patch(`/crm/employees/${encodeURIComponent(employeeId)}/status`, { status }).then(unwrap),
      employeeProfile: (employeeId) => api.get(`/crm/employees/${encodeURIComponent(employeeId)}/profile`).then(unwrap),
      updateEmployeeProfile: (employeeId, payload) => api.patch(`/crm/employees/${encodeURIComponent(employeeId)}/profile`, payload || {}).then(unwrap),
      employeeLeads: (employeeId, params) => api.get(`/crm/employees/${encodeURIComponent(employeeId)}/leads`, { params }).then(unwrap),
      employeeActivities: (employeeId, params) => api.get(`/crm/employees/${encodeURIComponent(employeeId)}/activities`, { params }).then(unwrap),
      employeeSessions: (employeeId, params) => api.get(`/crm/employees/${encodeURIComponent(employeeId)}/sessions`, { params }).then(unwrap),
      employeeRequests: (params) => api.get("/crm/employee-requests", { params }).then(unwrap),
      decideEmployeeRequest: (requestId, payload) => api.post(`/crm/employee-requests/${encodeURIComponent(requestId)}/decide`, payload || {}).then(unwrap),
      verifyEmployeeEmailOtp: (employeeId, payload) => api.post(`/crm/employees/${encodeURIComponent(employeeId)}/verify-email-otp`, payload || {}).then(unwrap),
      sendEmployeeResetLink: (employeeId) => api.post(`/crm/employees/${encodeURIComponent(employeeId)}/send-reset-link`, {}).then(unwrap),
      resetEmployeePassword: (employeeId, payload) => api.post(`/crm/employees/${encodeURIComponent(employeeId)}/reset-password`, payload || {}).then(unwrap),
      manualAssignLead: (phone, payload) => api.post(`/crm/leads/${encodeURIComponent(phone)}/assign`, payload || {}).then(unwrap),
      conversationEvents: (phone, params) => api.get(`/crm/conversations/${encodeURIComponent(phone)}/events`, { params }).then(unwrap),
    },
  };
}
