import { Button } from "@components/ui/Button";
import { Input } from "@components/ui/Input";
import { Modal } from "@components/ui/Modal";

export function EmployeeProfileActionModals(props: any) {
  const { editOpen, setEditOpen, editForm, setEditForm, busy, sendResetLink, employee, updateStatus, saveProfileEdit, resetModalOpen, setResetModalOpen, resetPwd, setResetPwd, resetPwd2, setResetPwd2, resetMode, setResetMode, setError, openConfirm, resetPasswordDirect, confirmOpen, setConfirmOpen, confirmTitle, confirmBody, confirmVariant, confirmAction, confirmCta } = props;
  return (
    <>
      <Modal isOpen={editOpen} onClose={() => setEditOpen(false)} title="Edit Employee Profile" className="max-w-[720px]"><div className="grid gap-3"><Input label="Name" value={editForm.name} onChange={(e) => setEditForm((s: any) => ({ ...s, name: e.target.value }))} /><Input label="Email" value={editForm.email} onChange={(e) => setEditForm((s: any) => ({ ...s, email: e.target.value }))} /><label className="text-xs font-bold text-slate-500 uppercase tracking-wider ml-1">Role</label><select className="h-10 rounded-[5px] border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-900" value={editForm.role} onChange={(e) => setEditForm((s: any) => ({ ...s, role: e.target.value }))}><option value="employee">Employee</option><option value="team_leader">Team Leader</option></select><Input label="Max Active Leads" value={editForm.maxActiveLeads || ""} onChange={(e) => setEditForm((s: any) => ({ ...s, maxActiveLeads: e.target.value.replace(/[^\d]/g, "") }))} /><div className="text-[11px] font-semibold text-slate-500">Used by FIXED_LIMIT routing. Blank means unlimited.</div><div className="pt-2 border-t border-slate-100 grid gap-2"><div className="text-[10px] font-black uppercase tracking-widest text-slate-500">Account</div><div className="flex flex-wrap items-center gap-2"><Button variant="outline" disabled={busy} onClick={() => { setResetMode("link"); setResetModalOpen(true); }}>Reset Password</Button><Button variant="outline" disabled={busy} onClick={sendResetLink}>Send Reset Link</Button><Button variant="outline" disabled={busy} onClick={() => updateStatus(employee?.status === "BLOCKED" ? "ACTIVE" : "BLOCKED")}>{employee?.status === "BLOCKED" ? "Unblock Employee" : "Block Employee"}</Button><Button variant="danger" disabled={busy} onClick={() => updateStatus("DELETED")}>Fire (Delete)</Button></div><div className="text-[11px] font-semibold text-slate-500">Fire/Delete is permanent. Email cannot be reused again for this workspace.</div></div><div className="flex items-center justify-end gap-2 pt-2 border-t border-slate-100"><Button variant="ghost" disabled={busy} onClick={() => setEditOpen(false)}>Close</Button><Button disabled={busy} onClick={saveProfileEdit}>{busy ? "Saving..." : "Save Changes"}</Button></div></div></Modal>
      <Modal isOpen={resetModalOpen} onClose={() => { setResetModalOpen(false); setResetPwd(""); setResetPwd2(""); setResetMode("link"); }} title="Reset Employee Password" className="max-w-[720px]"><div className="grid gap-3"><div className="text-sm font-semibold text-slate-600">Choose how you want to reset password.</div><div className="flex flex-wrap gap-2"><Button variant={resetMode === "link" ? "primary" : "outline"} onClick={() => setResetMode("link")}>Send Reset Link</Button><Button variant={resetMode === "direct" ? "primary" : "outline"} onClick={() => setResetMode("direct")}>Set New Password</Button></div>{resetMode === "link" ? <div className="grid gap-3"><div className="text-xs font-semibold text-slate-500">Employee will reset password using the link sent to their email.</div><Button variant="outline" disabled={busy} onClick={() => { setResetModalOpen(false); sendResetLink(); }}>Send Link</Button></div> : <div className="grid gap-3"><Input label="New password" type="password" value={resetPwd} onChange={(e) => setResetPwd(e.target.value)} /><Input label="Confirm password" type="password" value={resetPwd2} onChange={(e) => setResetPwd2(e.target.value)} /><Button variant="outline" disabled={busy} onClick={() => { const p1 = String(resetPwd || ""); const p2 = String(resetPwd2 || ""); if (p1.length < 8) { setError("Password must be at least 8 characters."); return; } if (p1 !== p2) { setError("Confirm password does not match."); return; } setResetModalOpen(false); openConfirm({ title: "Confirm Reset Password", body: "This will immediately log the employee out from all sessions. Continue?", cta: "Reset Password", variant: "danger", action: async () => { setConfirmOpen(false); await resetPasswordDirect(p1); } }); }}>Reset Password</Button></div>}</div></Modal>
      <Modal isOpen={confirmOpen} onClose={() => setConfirmOpen(false)} title={confirmTitle} className="max-w-[620px]"><div className="grid gap-4"><div className="text-sm font-semibold text-slate-700">{confirmBody}</div><div className="flex items-center justify-end gap-2"><Button variant="ghost" onClick={() => setConfirmOpen(false)}>Cancel</Button><Button variant={confirmVariant === "danger" ? "danger" : "primary"} disabled={!confirmAction} onClick={() => { if (!confirmAction) return; void confirmAction(); }}>{confirmCta}</Button></div></div></Modal>
    </>
  );
}
